DROP TABLE EXODBC.DATETYPES_TMP;

CREATE TABLE EXODBC.DATETYPES_TMP (
		IDDATETYPES INTEGER NOT NULL, 
		TDATE DATE, 
		TTIME TIME, 
		TTIMESTAMP TIMESTAMP
	);
	
ALTER TABLE EXODBC.DATETYPES_TMP ADD CONSTRAINT DATETYPES_TMP_PK PRIMARY KEY ( IDDATETYPES );	
