DROP TABLE EXODBC.BLOBTYPES_TMP

CREATE TABLE EXODBC.BLOBTYPES_TMP (
		IDBLOBTYPES INTEGER NOT NULL, 
		TBLOB CHAR (16) FOR BIT DATA, 
		TVARBLOB_20 VARCHAR (20) FOR BIT DATA
	);

ALTER TABLE EXODBC.BLOBTYPES_TMP ADD CONSTRAINT BLOBTYPES_TMP_PK PRIMARY KEY ( IDBLOBTYPES );