DROP TABLE EXODBC.NOT_SUPPORTED_TMP;

CREATE TABLE EXODBC.NOT_SUPPORTED_TMP (
		IDNOT_SUPPORTED INTEGER NOT NULL, 
		INT1 INTEGER, 
		XML XML, 
		INT2 INTEGER
	);

ALTER TABLE EXODBC.NOT_SUPPORTED_TMP ADD CONSTRAINT NOT_SUPPORTED_TMP_PK PRIMARY KEY (IDNOT_SUPPORTED);
