DROP TABLE EXODBC.NUMERICTYPES_TMP;

CREATE TABLE EXODBC.NUMERICTYPES_TMP (
		IDNUMERICTYPES INTEGER NOT NULL, 
		TDECIMAL_18_0 DECIMAL(18 , 0), 
		TDECIMAL_18_10 DECIMAL(18 , 10), 
		TDECIMAL_5_3 DECIMAL(5 , 3)
	);
	
ALTER TABLE EXODBC.NUMERICTYPES_TMP ADD CONSTRAINT NUMERICTYPES_TMP_PK PRIMARY KEY (IDNUMERICTYPES);

