DROP TABLE EXODBC.INTEGERTABLE;

CREATE TABLE EXODBC.INTEGERTABLE (
		IDINTEGERTABLE INTEGER NOT NULL, 
		TINT1 INTEGER, 
		TINT2 INTEGER, 
		TINT3 INTEGER
	);

ALTER TABLE EXODBC.INTEGERTABLE ADD CONSTRAINT INTEGERTABLE_PK PRIMARY KEY ( IDINTEGERTABLE );		
	
INSERT INTO EXODBC.INTEGERTABLE (IDINTEGERTABLE, TINT1, TINT2, TINT3) VALUES (1,2,3,4);
INSERT INTO EXODBC.INTEGERTABLE (IDINTEGERTABLE, TINT1, TINT2, TINT3) VALUES (2,20,NULL,40);
