DROP TABLE EXODBC.NOT_SUPPORTED;

CREATE TABLE EXODBC.NOT_SUPPORTED (
		IDNOT_SUPPORTED INTEGER NOT NULL, 
		INT1 INTEGER, 
		XML XML, 
		INT2 INTEGER
	);

ALTER TABLE EXODBC.NOT_SUPPORTED ADD CONSTRAINT NOT_SUPPORTED_PK PRIMARY KEY (IDNOT_SUPPORTED);
	
INSERT INTO EXODBC.NOT_SUPPORTED (IDNOT_SUPPORTED, INT1, XML, INT2) VALUES (1, 10, NULL, 12);
