DROP TABLE EXODBC.INTEGERTYPES_TMP;

CREATE TABLE EXODBC.INTEGERTYPES_TMP (
		IDINTEGERTYPES INTEGER NOT NULL, 
		TSMALLINT SMALLINT, 
		TINT INTEGER, 
		TBIGINT BIGINT
	);
	
ALTER TABLE EXODBC.INTEGERTYPES_TMP ADD CONSTRAINT INTEGERTYPES_TMP_PK PRIMARY KEY ( IDINTEGERTYPES );		
