DROP TABLE EXODBC.UNICODETABLE_TMP;

CREATE TABLE EXODBC.UNICODETABLE_TMP (
		IDUNICODETABLE INTEGER NOT NULL, 
		CONTENT VARCHAR(255)
	);
	
ALTER TABLE EXODBC.UNICODETABLE_TMP ADD CONSTRAINT IDUNICODETABLE_TMP_PK PRIMARY KEY ( IDUNICODETABLE );		
