--<ScriptOptions statementTerminator=";"/>

ALTER TABLE "EXODBC"."BLOBTYPES" DROP CONSTRAINT "SQL141228132855030";

ALTER TABLE "EXODBC"."BLOBTYPES_TMP" DROP CONSTRAINT "SQL150110161847350";

ALTER TABLE "EXODBC"."CHARTABLE" DROP CONSTRAINT "SQL140824171952370";

ALTER TABLE "EXODBC"."CHARTYPES" DROP CONSTRAINT "SQL140824171952410";

ALTER TABLE "EXODBC"."CHARTYPES_TMP" DROP CONSTRAINT "CHARTYPES_TMP_PK";

ALTER TABLE "EXODBC"."DATETYPES" DROP CONSTRAINT "SQL140824171952450";

ALTER TABLE "EXODBC"."DATETYPES_TMP" DROP CONSTRAINT "SQL140824171952470";

ALTER TABLE "EXODBC"."FLOATTYPES" DROP CONSTRAINT "SQL140824171952500";

ALTER TABLE "EXODBC"."FLOATTYPES_TMP" DROP CONSTRAINT "SQL140824171952520";

ALTER TABLE "EXODBC"."INTEGERTYPES" DROP CONSTRAINT "SQL140824171952550";

ALTER TABLE "EXODBC"."INTEGERTYPES_TMP" DROP CONSTRAINT "SQL140824171952580";

ALTER TABLE "EXODBC"."MULTIKEY" DROP CONSTRAINT "SQL150102170442310";

ALTER TABLE "EXODBC"."NUMERICTYPES" DROP CONSTRAINT "SQL140824171952600";

ALTER TABLE "EXODBC"."NUMERICTYPES_TMP" DROP CONSTRAINT "SQL140824171952630";

ALTER TABLE "EXODBC"."SELECTONLY" DROP CONSTRAINT "SQL141231030613260";

DROP TABLE "EXODBC"."BLOBTYPES";

DROP TABLE "EXODBC"."BLOBTYPES_TMP";

DROP TABLE "EXODBC"."CHARTABLE";

DROP TABLE "EXODBC"."CHARTYPES";

DROP TABLE "EXODBC"."CHARTYPES_TMP";

DROP TABLE "EXODBC"."DATETYPES";

DROP TABLE "EXODBC"."DATETYPES_TMP";

DROP TABLE "EXODBC"."FLOATTYPES";

DROP TABLE "EXODBC"."FLOATTYPES_TMP";

DROP TABLE "EXODBC"."INTEGERTYPES";

DROP TABLE "EXODBC"."INTEGERTYPES_TMP";

DROP TABLE "EXODBC"."MULTIKEY";

DROP TABLE "EXODBC"."NUMERICTYPES";

DROP TABLE "EXODBC"."NUMERICTYPES_TMP";

DROP TABLE "EXODBC"."SELECTONLY";

DROP SCHEMA "EXODBC" RESTRICT;

CREATE SCHEMA "EXODBC" AUTHORIZATION "EXODBC";

CREATE TABLE "EXODBC"."BLOBTYPES" (
		"IDBLOBTYPES" INTEGER NOT NULL, 
		"TBLOB" CHAR (16) FOR BIT DATA, 
		"TVARBLOB_20" VARCHAR (20) FOR BIT DATA
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "EXODBC"."BLOBTYPES_TMP" (
		"IDBLOBTYPES" INTEGER NOT NULL, 
		"TBLOB" CHAR (16) FOR BIT DATA, 
		"TVARBLOB_20" VARCHAR (20) FOR BIT DATA
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "EXODBC"."CHARTABLE" (
		"IDCHARTABLE" INTEGER NOT NULL, 
		"COL2" CHAR(128), 
		"COL3" CHAR(128), 
		"COL4" CHAR(128)
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "EXODBC"."CHARTYPES" (
		"IDCHARTYPES" INTEGER NOT NULL, 
		"TVARCHAR" VARCHAR(128), 
		"TCHAR" CHAR(128), 
		"TVARCHAR_10" VARCHAR(10), 
		"TCHAR_10" CHAR(10)
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "EXODBC"."CHARTYPES_TMP" (
		"IDCHARTYPES" INTEGER NOT NULL, 
		"TVARCHAR" VARCHAR(128), 
		"TCHAR" CHAR(128), 
		"TVARCHAR_10" VARCHAR(10), 
		"TCHAR_10" CHAR(10)
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "EXODBC"."DATETYPES" (
		"IDDATETYPES" INTEGER NOT NULL, 
		"TDATE" DATE, 
		"TTIME" TIME, 
		"TTIMESTAMP" TIMESTAMP
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "EXODBC"."DATETYPES_TMP" (
		"IDDATETYPES" INTEGER NOT NULL, 
		"TDATE" DATE, 
		"TTIME" TIME, 
		"TTIMESTAMP" TIMESTAMP
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "EXODBC"."FLOATTYPES" (
		"IDFLOATTYPES" INTEGER NOT NULL, 
		"TDOUBLE" DOUBLE, 
		"TFLOAT" DOUBLE
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "EXODBC"."FLOATTYPES_TMP" (
		"IDFLOATTYPES" INTEGER NOT NULL, 
		"TDOUBLE" DOUBLE, 
		"TFLOAT" DOUBLE
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "EXODBC"."INTEGERTYPES" (
		"IDINTEGERTYPES" INTEGER NOT NULL, 
		"TSMALLINT" SMALLINT, 
		"TINT" INTEGER, 
		"TBIGINT" BIGINT
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "EXODBC"."INTEGERTYPES_TMP" (
		"IDINTEGERTYPES" INTEGER NOT NULL, 
		"TSMALLINT" SMALLINT, 
		"TINT" INTEGER, 
		"TBIGINT" BIGINT
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "EXODBC"."MULTIKEY" (
		"ID1" INTEGER NOT NULL, 
		"ID2" INTEGER NOT NULL, 
		"VALUE" VARCHAR(10), 
		"ID3" INTEGER NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "EXODBC"."NUMERICTYPES" (
		"IDNUMERICTYPES" INTEGER NOT NULL, 
		"TDECIMAL_18_0" DECIMAL(18 , 0), 
		"TDECIMAL_18_10" DECIMAL(18 , 10), 
		"TDECIMAL_5_3" DECIMAL(5 , 3)
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "EXODBC"."NUMERICTYPES_TMP" (
		"IDNUMERICTYPES" INTEGER NOT NULL, 
		"TDECIMAL_18_0" DECIMAL(18 , 0), 
		"TDECIMAL_18_10" DECIMAL(18 , 10), 
		"TDECIMAL_5_3" DECIMAL(5 , 3)
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "EXODBC"."SELECTONLY" (
		"IDSELECTONLY" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE -2147483648 MAXVALUE 2147483647 NO CYCLE CACHE 20 NO ORDER ), 
		"VALUE" INTEGER
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	COMPRESS NO;

ALTER TABLE "EXODBC"."BLOBTYPES" ADD CONSTRAINT "SQL141228132855030" PRIMARY KEY
	("IDBLOBTYPES");

ALTER TABLE "EXODBC"."BLOBTYPES_TMP" ADD CONSTRAINT "SQL150110161847350" PRIMARY KEY
	("IDBLOBTYPES");

ALTER TABLE "EXODBC"."CHARTABLE" ADD CONSTRAINT "SQL140824171952370" PRIMARY KEY
	("IDCHARTABLE");

ALTER TABLE "EXODBC"."CHARTYPES" ADD CONSTRAINT "SQL140824171952410" PRIMARY KEY
	("IDCHARTYPES");

ALTER TABLE "EXODBC"."CHARTYPES_TMP" ADD CONSTRAINT "CHARTYPES_TMP_PK" PRIMARY KEY
	("IDCHARTYPES");

ALTER TABLE "EXODBC"."DATETYPES" ADD CONSTRAINT "SQL140824171952450" PRIMARY KEY
	("IDDATETYPES");

ALTER TABLE "EXODBC"."DATETYPES_TMP" ADD CONSTRAINT "SQL140824171952470" PRIMARY KEY
	("IDDATETYPES");

ALTER TABLE "EXODBC"."FLOATTYPES" ADD CONSTRAINT "SQL140824171952500" PRIMARY KEY
	("IDFLOATTYPES");

ALTER TABLE "EXODBC"."FLOATTYPES_TMP" ADD CONSTRAINT "SQL140824171952520" PRIMARY KEY
	("IDFLOATTYPES");

ALTER TABLE "EXODBC"."INTEGERTYPES" ADD CONSTRAINT "SQL140824171952550" PRIMARY KEY
	("IDINTEGERTYPES");

ALTER TABLE "EXODBC"."INTEGERTYPES_TMP" ADD CONSTRAINT "SQL140824171952580" PRIMARY KEY
	("IDINTEGERTYPES");

ALTER TABLE "EXODBC"."MULTIKEY" ADD CONSTRAINT "SQL150102170442310" PRIMARY KEY
	("ID1", 
	 "ID2", 
	 "ID3");

ALTER TABLE "EXODBC"."NUMERICTYPES" ADD CONSTRAINT "SQL140824171952600" PRIMARY KEY
	("IDNUMERICTYPES");

ALTER TABLE "EXODBC"."NUMERICTYPES_TMP" ADD CONSTRAINT "SQL140824171952630" PRIMARY KEY
	("IDNUMERICTYPES");

ALTER TABLE "EXODBC"."SELECTONLY" ADD CONSTRAINT "SQL141231030613260" PRIMARY KEY
	("IDSELECTONLY");

GRANT ALTER ON TABLE "EXODBC"."BLOBTYPES" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT ALTER ON TABLE "EXODBC"."CHARTABLE" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT ALTER ON TABLE "EXODBC"."CHARTYPES" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT ALTER ON TABLE "EXODBC"."CHARTYPES_TMP" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT ALTER ON TABLE "EXODBC"."DATETYPES" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT ALTER ON TABLE "EXODBC"."DATETYPES_TMP" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT ALTER ON TABLE "EXODBC"."FLOATTYPES" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT ALTER ON TABLE "EXODBC"."FLOATTYPES_TMP" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT ALTER ON TABLE "EXODBC"."INTEGERTYPES" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT ALTER ON TABLE "EXODBC"."INTEGERTYPES_TMP" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT ALTER ON TABLE "EXODBC"."NUMERICTYPES" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT ALTER ON TABLE "EXODBC"."NUMERICTYPES_TMP" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT ALTER ON TABLE "EXODBC"."SELECTONLY" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT CONTROL ON TABLE "EXODBC"."BLOBTYPES" TO USER "DB2ADMIN";

GRANT CONTROL ON TABLE "EXODBC"."CHARTABLE" TO USER "DB2ADMIN";

GRANT CONTROL ON TABLE "EXODBC"."CHARTYPES" TO USER "DB2ADMIN";

GRANT CONTROL ON TABLE "EXODBC"."CHARTYPES_TMP" TO USER "DB2ADMIN";

GRANT CONTROL ON TABLE "EXODBC"."DATETYPES" TO USER "DB2ADMIN";

GRANT CONTROL ON TABLE "EXODBC"."DATETYPES_TMP" TO USER "DB2ADMIN";

GRANT CONTROL ON TABLE "EXODBC"."FLOATTYPES" TO USER "DB2ADMIN";

GRANT CONTROL ON TABLE "EXODBC"."FLOATTYPES_TMP" TO USER "DB2ADMIN";

GRANT CONTROL ON TABLE "EXODBC"."INTEGERTYPES" TO USER "DB2ADMIN";

GRANT CONTROL ON TABLE "EXODBC"."INTEGERTYPES_TMP" TO USER "DB2ADMIN";

GRANT CONTROL ON TABLE "EXODBC"."NUMERICTYPES" TO USER "DB2ADMIN";

GRANT CONTROL ON TABLE "EXODBC"."NUMERICTYPES_TMP" TO USER "DB2ADMIN";

GRANT CONTROL ON TABLE "EXODBC"."SELECTONLY" TO USER "DB2ADMIN";

GRANT DELETE ON TABLE "EXODBC"."BLOBTYPES" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT DELETE ON TABLE "EXODBC"."CHARTABLE" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT DELETE ON TABLE "EXODBC"."CHARTYPES" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT DELETE ON TABLE "EXODBC"."CHARTYPES_TMP" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT DELETE ON TABLE "EXODBC"."DATETYPES" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT DELETE ON TABLE "EXODBC"."DATETYPES_TMP" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT DELETE ON TABLE "EXODBC"."FLOATTYPES" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT DELETE ON TABLE "EXODBC"."FLOATTYPES_TMP" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT DELETE ON TABLE "EXODBC"."INTEGERTYPES" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT DELETE ON TABLE "EXODBC"."INTEGERTYPES_TMP" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT DELETE ON TABLE "EXODBC"."NUMERICTYPES" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT DELETE ON TABLE "EXODBC"."NUMERICTYPES_TMP" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT DELETE ON TABLE "EXODBC"."SELECTONLY" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT INDEX ON TABLE "EXODBC"."BLOBTYPES" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT INDEX ON TABLE "EXODBC"."CHARTABLE" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT INDEX ON TABLE "EXODBC"."CHARTYPES" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT INDEX ON TABLE "EXODBC"."CHARTYPES_TMP" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT INDEX ON TABLE "EXODBC"."DATETYPES" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT INDEX ON TABLE "EXODBC"."DATETYPES_TMP" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT INDEX ON TABLE "EXODBC"."FLOATTYPES" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT INDEX ON TABLE "EXODBC"."FLOATTYPES_TMP" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT INDEX ON TABLE "EXODBC"."INTEGERTYPES" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT INDEX ON TABLE "EXODBC"."INTEGERTYPES_TMP" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT INDEX ON TABLE "EXODBC"."NUMERICTYPES" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT INDEX ON TABLE "EXODBC"."NUMERICTYPES_TMP" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT INDEX ON TABLE "EXODBC"."SELECTONLY" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT INSERT ON TABLE "EXODBC"."BLOBTYPES" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT INSERT ON TABLE "EXODBC"."CHARTABLE" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT INSERT ON TABLE "EXODBC"."CHARTYPES" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT INSERT ON TABLE "EXODBC"."CHARTYPES_TMP" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT INSERT ON TABLE "EXODBC"."DATETYPES" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT INSERT ON TABLE "EXODBC"."DATETYPES_TMP" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT INSERT ON TABLE "EXODBC"."FLOATTYPES" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT INSERT ON TABLE "EXODBC"."FLOATTYPES_TMP" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT INSERT ON TABLE "EXODBC"."INTEGERTYPES" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT INSERT ON TABLE "EXODBC"."INTEGERTYPES_TMP" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT INSERT ON TABLE "EXODBC"."NUMERICTYPES" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT INSERT ON TABLE "EXODBC"."NUMERICTYPES_TMP" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT INSERT ON TABLE "EXODBC"."SELECTONLY" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT REFERENCES ON TABLE "EXODBC"."BLOBTYPES" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT REFERENCES ON TABLE "EXODBC"."CHARTABLE" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT REFERENCES ON TABLE "EXODBC"."CHARTYPES" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT REFERENCES ON TABLE "EXODBC"."CHARTYPES_TMP" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT REFERENCES ON TABLE "EXODBC"."DATETYPES" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT REFERENCES ON TABLE "EXODBC"."DATETYPES_TMP" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT REFERENCES ON TABLE "EXODBC"."FLOATTYPES" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT REFERENCES ON TABLE "EXODBC"."FLOATTYPES_TMP" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT REFERENCES ON TABLE "EXODBC"."INTEGERTYPES" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT REFERENCES ON TABLE "EXODBC"."INTEGERTYPES_TMP" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT REFERENCES ON TABLE "EXODBC"."NUMERICTYPES" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT REFERENCES ON TABLE "EXODBC"."NUMERICTYPES_TMP" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT REFERENCES ON TABLE "EXODBC"."SELECTONLY" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT SELECT ON TABLE "EXODBC"."BLOBTYPES" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT SELECT ON TABLE "EXODBC"."CHARTABLE" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT SELECT ON TABLE "EXODBC"."CHARTYPES" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT SELECT ON TABLE "EXODBC"."CHARTYPES_TMP" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT SELECT ON TABLE "EXODBC"."DATETYPES" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT SELECT ON TABLE "EXODBC"."DATETYPES_TMP" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT SELECT ON TABLE "EXODBC"."FLOATTYPES" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT SELECT ON TABLE "EXODBC"."FLOATTYPES_TMP" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT SELECT ON TABLE "EXODBC"."INTEGERTYPES" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT SELECT ON TABLE "EXODBC"."INTEGERTYPES_TMP" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT SELECT ON TABLE "EXODBC"."NUMERICTYPES" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT SELECT ON TABLE "EXODBC"."NUMERICTYPES_TMP" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT SELECT ON TABLE "EXODBC"."SELECTONLY" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT UPDATE ON TABLE "EXODBC"."BLOBTYPES" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT UPDATE ON TABLE "EXODBC"."CHARTABLE" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT UPDATE ON TABLE "EXODBC"."CHARTYPES" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT UPDATE ON TABLE "EXODBC"."CHARTYPES_TMP" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT UPDATE ON TABLE "EXODBC"."DATETYPES" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT UPDATE ON TABLE "EXODBC"."DATETYPES_TMP" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT UPDATE ON TABLE "EXODBC"."FLOATTYPES" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT UPDATE ON TABLE "EXODBC"."FLOATTYPES_TMP" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT UPDATE ON TABLE "EXODBC"."INTEGERTYPES" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT UPDATE ON TABLE "EXODBC"."INTEGERTYPES_TMP" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT UPDATE ON TABLE "EXODBC"."NUMERICTYPES" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT UPDATE ON TABLE "EXODBC"."NUMERICTYPES_TMP" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT UPDATE ON TABLE "EXODBC"."SELECTONLY" TO USER "DB2ADMIN" WITH GRANT OPTION;

