--<ScriptOptions statementTerminator=";"/>

CREATE LARGE TABLESPACE "SYSTOOLSPACE"
	IN DATABASE PARTITION GROUP "IBMCATGROUP"
	PAGESIZE 4 K
	MANAGED BY AUTOMATIC STORAGE
	AUTORESIZE YES
	EXTENTSIZE 4
	BUFFERPOOL "IBMDEFAULTBP"
	OVERHEAD INHERIT
	TRANSFERRATE INHERIT
	DATA TAG INHERIT
	USING STOGROUP "IBMSTOGROUP"
	NO FILE SYSTEM CACHING;

CREATE LARGE TABLESPACE "USERSPACE1"
	IN DATABASE PARTITION GROUP "IBMDEFAULTGROUP"
	PAGESIZE 4 K
	MANAGED BY AUTOMATIC STORAGE
	AUTORESIZE YES
	EXTENTSIZE 32
	BUFFERPOOL "IBMDEFAULTBP"
	OVERHEAD INHERIT
	TRANSFERRATE INHERIT
	DATA TAG INHERIT
	USING STOGROUP "IBMSTOGROUP"
	NO FILE SYSTEM CACHING;

CREATE REGULAR TABLESPACE "SYSCATSPACE"
	IN DATABASE PARTITION GROUP "IBMCATGROUP"
	PAGESIZE 4 K
	MANAGED BY AUTOMATIC STORAGE
	AUTORESIZE YES
	EXTENTSIZE 4
	BUFFERPOOL "IBMDEFAULTBP"
	OVERHEAD INHERIT
	TRANSFERRATE INHERIT
	DATA TAG NONE
	USING STOGROUP "IBMSTOGROUP"
	DROPPED TABLE RECOVERY OFF
	NO FILE SYSTEM CACHING;

CREATE SYSTEM TEMPORARY TABLESPACE "TEMPSPACE1"
	IN DATABASE PARTITION GROUP "IBMTEMPGROUP"
	PAGESIZE 4 K
	MANAGED BY AUTOMATIC STORAGE
	EXTENTSIZE 32
	BUFFERPOOL "IBMDEFAULTBP"
	OVERHEAD INHERIT
	TRANSFERRATE INHERIT
	DATA TAG NONE
	USING STOGROUP "IBMSTOGROUP"
	FILE SYSTEM CACHING;

CREATE SCHEMA "NULLID" AUTHORIZATION "SYSIBM";

CREATE SCHEMA "SQLJ" AUTHORIZATION "SYSIBM";

CREATE SCHEMA "SYSCAT" AUTHORIZATION "SYSIBM";

CREATE SCHEMA "SYSFUN" AUTHORIZATION "SYSIBM";

CREATE SCHEMA "SYSIBM" AUTHORIZATION "SYSIBM";

CREATE SCHEMA "SYSIBMADM" AUTHORIZATION "SYSIBM";

CREATE SCHEMA "SYSIBMINTERNAL" AUTHORIZATION "SYSIBM";

CREATE SCHEMA "SYSIBMTS" AUTHORIZATION "SYSIBM";

CREATE SCHEMA "SYSPROC" AUTHORIZATION "SYSIBM";

CREATE SCHEMA "SYSPUBLIC" AUTHORIZATION "SYSIBM";

CREATE SCHEMA "SYSSTAT" AUTHORIZATION "SYSIBM";

CREATE SCHEMA "SYSTOOLS" AUTHORIZATION "SYSIBM";

CREATE SCHEMA "WXODBC3" AUTHORIZATION "DB2ADMIN";

CREATE TABLE "SYSIBM"."SYSATTRIBUTES" (
		"TYPESCHEMA" VARCHAR(128) NOT NULL, 
		"TYPENAME" VARCHAR(128) NOT NULL, 
		"ATTR_NAME" VARCHAR(128) NOT NULL, 
		"ATTR_TYPESCHEMA" VARCHAR(128) NOT NULL, 
		"ATTR_TYPENAME" VARCHAR(128) NOT NULL, 
		"ORDINAL" SMALLINT NOT NULL, 
		"LENGTH" INTEGER NOT NULL, 
		"SCALE" SMALLINT NOT NULL, 
		"CODEPAGE" SMALLINT NOT NULL, 
		"LOGGED" CHAR(1) NOT NULL, 
		"COMPACT" CHAR(1) NOT NULL, 
		"TARGET_TYPESCHEMA" VARCHAR(128), 
		"TARGET_TYPENAME" VARCHAR(128), 
		"SOURCE_TYPESCHEMA" VARCHAR(128) NOT NULL, 
		"SOURCE_TYPENAME" VARCHAR(128) NOT NULL, 
		"JAVA_FIELDNAME" VARCHAR(256), 
		"COLLATIONID" CHAR (8) FOR BIT DATA, 
		"TYPEMODULEID" INTEGER, 
		"ATTR_TYPEMODULEID" INTEGER, 
		"TARGET_TYPEMODULEID" INTEGER, 
		"SOURCE_TYPEMODULEID" INTEGER, 
		"NULLS" CHAR(1) NOT NULL, 
		"QUALIFIER" VARCHAR(128), 
		"FUNC_PATH" CLOB(2048) INLINE LENGTH 92, 
		"DEFAULT" CLOB(65536) INLINE LENGTH 116, 
		"STRINGUNITS" CHAR(1) NOT NULL, 
		"ENVID" INTEGER NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSAUDITEXCEPTIONS" (
		"OBJECTSCHEMA" VARCHAR(128), 
		"OBJECTNAME" VARCHAR(128) NOT NULL, 
		"OBJECTTYPE" CHAR(1) NOT NULL, 
		"SUBOBJECTTYPE" CHAR(1) NOT NULL, 
		"EXOBJECTSCHEMA" VARCHAR(128), 
		"EXOBJECTNAME" VARCHAR(128) NOT NULL, 
		"EXOBJECTTYPE" CHAR(1) NOT NULL, 
		"SUBEXOBJECTTYPE" CHAR(1) NOT NULL, 
		"RESERVED1" BLOB(1024) INLINE LENGTH 68
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSAUDITPOLICIES" (
		"AUDITPOLICYNAME" VARCHAR(128) NOT NULL, 
		"AUDITPOLICYID" INTEGER NOT NULL, 
		"CREATE_TIME" TIMESTAMP NOT NULL, 
		"ALTER_TIME" TIMESTAMP NOT NULL, 
		"AUDITSTATUS" CHAR(1) NOT NULL, 
		"CONTEXTSTATUS" CHAR(1) NOT NULL, 
		"VALIDATESTATUS" CHAR(1) NOT NULL, 
		"CHECKINGSTATUS" CHAR(1) NOT NULL, 
		"SECMAINTSTATUS" CHAR(1) NOT NULL, 
		"OBJMAINTSTATUS" CHAR(1) NOT NULL, 
		"SYSADMINSTATUS" CHAR(1) NOT NULL, 
		"EXECUTESTATUS" CHAR(1) NOT NULL, 
		"EXECUTEWITHDATA" CHAR(1) NOT NULL, 
		"ERRORTYPE" CHAR(1) NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSAUDITUSE" (
		"OBJECTNAME" VARCHAR(128) NOT NULL, 
		"OBJECTTYPE" CHAR(1) NOT NULL, 
		"SUBOBJECTTYPE" CHAR(1) NOT NULL, 
		"AUDITPOLICYID" INTEGER NOT NULL, 
		"AUDITEXCEPTIONENABLED" CHAR(1) NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSBUFFERPOOLNODES" (
		"BUFFERPOOLID" INTEGER NOT NULL, 
		"NODENUM" SMALLINT NOT NULL, 
		"NPAGES" INTEGER NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSBUFFERPOOLS" (
		"BPNAME" VARCHAR(128) NOT NULL, 
		"BUFFERPOOLID" INTEGER NOT NULL, 
		"NGNAME" VARCHAR(128), 
		"NPAGES" INTEGER NOT NULL, 
		"PAGESIZE" INTEGER NOT NULL, 
		"NUMBLOCKPAGES" INTEGER NOT NULL, 
		"BLOCKSIZE" INTEGER NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSCHECKS" (
		"NAME" VARCHAR(128) NOT NULL, 
		"DEFINER" VARCHAR(128) NOT NULL, 
		"TBNAME" VARCHAR(128) NOT NULL, 
		"TBCREATOR" VARCHAR(128) NOT NULL, 
		"CREATE_TIME" TIMESTAMP NOT NULL, 
		"FUNC_PATH" CLOB(2048) INLINE LENGTH 92 NOT NULL, 
		"TEXT" CLOB(2097152) INLINE LENGTH 164 NOT NULL, 
		"QUALIFIER" VARCHAR(128) NOT NULL, 
		"TYPE" CHAR(1) NOT NULL, 
		"PERCENTVALID" SMALLINT NOT NULL, 
		"DEFINERTYPE" CHAR(1) NOT NULL, 
		"COLLATIONID" CHAR (8) FOR BIT DATA NOT NULL, 
		"COLLATIONID_ORDERBY" CHAR (8) FOR BIT DATA NOT NULL, 
		"STRINGUNITS" CHAR(1) NOT NULL, 
		"ENVID" INTEGER NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSCODEPROPERTIES" (
		"OBJECT_TYPE" CHAR(1) NOT NULL, 
		"OBJECT_ID" INTEGER NOT NULL, 
		"LIB_ID" INTEGER, 
		"LIBVERSION" INTEGER, 
		"TRACE_LEVEL" CHAR(1) NOT NULL, 
		"DIAGNOSTIC_LEVEL" CHAR(1) NOT NULL, 
		"DEBUG_DATA" CLOB(1048576) INLINE LENGTH 164, 
		"CHECKOUT_USERID" VARCHAR(128), 
		"PRECOMPILE_OPTIONS" VARCHAR(1024), 
		"COMPILE_OPTIONS" VARCHAR(1024), 
		"SQL_COMPILED_CODE" BLOB(10485760) INLINE LENGTH 196
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSCOLAUTH" (
		"GRANTOR" VARCHAR(128) NOT NULL, 
		"GRANTEE" VARCHAR(128) NOT NULL, 
		"GRANTEETYPE" CHAR(1) NOT NULL, 
		"CREATOR" VARCHAR(128) NOT NULL, 
		"TNAME" VARCHAR(128) NOT NULL, 
		"PRIVTYPE" CHAR(1) NOT NULL, 
		"COLNAME" VARCHAR(128) NOT NULL, 
		"GRANTABLE" CHAR(1) NOT NULL, 
		"COLNO" SMALLINT NOT NULL, 
		"GRANTORTYPE" CHAR(1) NOT NULL, 
		"GRANTEEROLEID" INTEGER, 
		"GRANTORROLEID" INTEGER
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSCOLCHECKS" (
		"CONSTNAME" VARCHAR(128) NOT NULL, 
		"TBNAME" VARCHAR(128) NOT NULL, 
		"TBCREATOR" VARCHAR(128) NOT NULL, 
		"COLNAME" VARCHAR(128) NOT NULL, 
		"USAGE" CHAR(1) NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSCOLDEPENDENCIES" (
		"BSCHEMA" VARCHAR(128) NOT NULL, 
		"BNAME" VARCHAR(128) NOT NULL, 
		"BCOLNAME" VARCHAR(128) NOT NULL, 
		"DSCHEMA" VARCHAR(128) NOT NULL, 
		"DNAME" VARCHAR(128) NOT NULL, 
		"DTYPE" CHAR(1) NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSCOLDIST" (
		"NAME" VARCHAR(128) NOT NULL, 
		"TBNAME" VARCHAR(128) NOT NULL, 
		"SCHEMA" VARCHAR(128) NOT NULL, 
		"TYPE" CHAR(1) NOT NULL, 
		"SEQNO" SMALLINT NOT NULL, 
		"COLVALUE" VARCHAR(254), 
		"VALCOUNT" BIGINT NOT NULL, 
		"DISTCOUNT" BIGINT
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSCOLGROUPDIST" (
		"COLGROUPID" INTEGER NOT NULL, 
		"TYPE" CHAR(1) NOT NULL, 
		"ORDINAL" SMALLINT NOT NULL, 
		"SEQNO" SMALLINT NOT NULL, 
		"COLVALUE" VARCHAR(254) NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSCOLGROUPDISTCOUNTS" (
		"COLGROUPID" INTEGER NOT NULL, 
		"TYPE" CHAR(1) NOT NULL, 
		"SEQNO" SMALLINT NOT NULL, 
		"VALCOUNT" BIGINT NOT NULL, 
		"DISTCOUNT" BIGINT NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSCOLGROUPS" (
		"COLGROUPSCHEMA" VARCHAR(128) NOT NULL, 
		"COLGROUPNAME" VARCHAR(128) NOT NULL, 
		"COLGROUPID" INTEGER NOT NULL, 
		"COLGROUPCARD" BIGINT NOT NULL, 
		"NUMFREQ_VALUES" SMALLINT NOT NULL, 
		"NUMQUANTILES" SMALLINT NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSCOLGROUPSCOLS" (
		"COLGROUPID" INTEGER NOT NULL, 
		"COLNAME" VARCHAR(128) NOT NULL, 
		"TABSCHEMA" VARCHAR(128) NOT NULL, 
		"TABNAME" VARCHAR(128) NOT NULL, 
		"ORDINAL" SMALLINT NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSCOLLATIONS" (
		"COLLATIONSCHEMA" VARCHAR(128) NOT NULL, 
		"COLLATIONNAME" VARCHAR(128) NOT NULL, 
		"OBJECTID" INTEGER NOT NULL, 
		"COLLATIONID" CHAR (8) FOR BIT DATA NOT NULL, 
		"SOURCECOLLATIONID" CHAR (8) FOR BIT DATA NOT NULL, 
		"OWNER" VARCHAR(128) NOT NULL, 
		"OWNERTYPE" CHAR(1) NOT NULL, 
		"COLLATION_DESC" BLOB(2097152) INLINE LENGTH 164
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSCOLOPTIONS" (
		"TABSCHEMA" VARCHAR(128) NOT NULL, 
		"TABNAME" VARCHAR(128) NOT NULL, 
		"COLNAME" VARCHAR(128) NOT NULL, 
		"OPTION" VARCHAR(128) NOT NULL, 
		"SETTING" CLOB(32768) INLINE LENGTH 116 NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSCOLPROPERTIES" (
		"COLNAME" VARCHAR(128) NOT NULL, 
		"TABNAME" VARCHAR(128) NOT NULL, 
		"TABSCHEMA" VARCHAR(128) NOT NULL, 
		"TARGET_TYPESCHEMA" VARCHAR(128), 
		"TARGET_TYPENAME" VARCHAR(128), 
		"SCOPE_TABSCHEMA" VARCHAR(128), 
		"SCOPE_TABNAME" VARCHAR(128), 
		"SPECIAL_PROPS" CHAR(8) NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSCOLUMNS" (
		"NAME" VARCHAR(128) NOT NULL, 
		"TBNAME" VARCHAR(128) NOT NULL, 
		"TBCREATOR" VARCHAR(128) NOT NULL, 
		"REMARKS" VARCHAR(254), 
		"COLTYPE" CHAR(8) NOT NULL, 
		"NULLS" CHAR(1) NOT NULL, 
		"CODEPAGE" SMALLINT NOT NULL, 
		"DBCSCODEPG" SMALLINT NOT NULL, 
		"LENGTH" SMALLINT NOT NULL, 
		"SCALE" SMALLINT NOT NULL, 
		"COLNO" SMALLINT NOT NULL, 
		"COLCARD" BIGINT NOT NULL, 
		"HIGH2KEY" VARCHAR(254), 
		"LOW2KEY" VARCHAR(254), 
		"AVGCOLLEN" INTEGER NOT NULL, 
		"KEYSEQ" SMALLINT, 
		"TYPENAME" VARCHAR(128) NOT NULL, 
		"TYPESCHEMA" VARCHAR(128) NOT NULL, 
		"DEFAULT" CLOB(65536) INLINE LENGTH 116, 
		"LONGLENGTH" INTEGER NOT NULL, 
		"LOGGED" CHAR(1) NOT NULL, 
		"COMPACT" CHAR(1) NOT NULL, 
		"NQUANTILES" SMALLINT NOT NULL, 
		"NMOSTFREQ" SMALLINT NOT NULL, 
		"COMPOSITE_CODEPAGE" SMALLINT NOT NULL, 
		"PARTKEYSEQ" SMALLINT, 
		"SOURCE_TABSCHEMA" VARCHAR(128), 
		"SOURCE_TABNAME" VARCHAR(128), 
		"HIDDEN" CHAR(1) NOT NULL, 
		"GENERATED" CHAR(1) NOT NULL, 
		"INLINE_LENGTH" INTEGER NOT NULL, 
		"NUMNULLS" BIGINT NOT NULL, 
		"AVGCOLLENCHAR" INTEGER NOT NULL, 
		"SUB_COUNT" SMALLINT NOT NULL, 
		"SUB_DELIM_LENGTH" SMALLINT NOT NULL, 
		"IDENTITY" CHAR(1) NOT NULL, 
		"COMPRESS" CHAR(1) NOT NULL, 
		"AVGDISTINCTPERPAGE" DOUBLE, 
		"PAGEVARIANCERATIO" DOUBLE, 
		"IMPLICITVALUE" VARCHAR(254), 
		"SECLABELID" INTEGER NOT NULL, 
		"COLLATIONID" CHAR (8) FOR BIT DATA, 
		"PCTINLINED" SMALLINT NOT NULL, 
		"PCTENCODED" SMALLINT NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSCOLUSE" (
		"TABSCHEMA" VARCHAR(128) NOT NULL, 
		"TABNAME" VARCHAR(128) NOT NULL, 
		"COLNAME" VARCHAR(128) NOT NULL, 
		"DIMENSION" SMALLINT NOT NULL, 
		"COLSEQ" SMALLINT NOT NULL, 
		"TYPE" CHAR(1) NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSCOMMENTS" (
		"OBJECTID" BIGINT NOT NULL, 
		"REMARKS" VARCHAR(254) NOT NULL, 
		"OBJECTTYPE" CHAR(1) NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSCONSTDEP" (
		"BNAME" VARCHAR(128) NOT NULL, 
		"BCREATOR" VARCHAR(128) NOT NULL, 
		"BTYPE" CHAR(1) NOT NULL, 
		"DTBNAME" VARCHAR(128) NOT NULL, 
		"DTBCREATOR" VARCHAR(128) NOT NULL, 
		"DCONSTNAME" VARCHAR(128) NOT NULL, 
		"BMODULEID" INTEGER
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSCONTEXTATTRIBUTES" (
		"CONTEXTID" INTEGER NOT NULL, 
		"ATTR_NAME" VARCHAR(128) NOT NULL, 
		"ATTR_TYPE" SMALLINT NOT NULL, 
		"ATTR_VALUE" VARCHAR(128) NOT NULL, 
		"ATTR_OPTIONS" VARCHAR(128)
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSCONTEXTS" (
		"CONTEXTNAME" VARCHAR(128) NOT NULL, 
		"CONTEXTID" INTEGER NOT NULL, 
		"SYSTEMAUTHID" VARCHAR(128) NOT NULL, 
		"DEFAULTCONTEXTROLE" VARCHAR(128), 
		"ROLEASOBJECTOWNER" CHAR(1) NOT NULL, 
		"CREATE_TIME" TIMESTAMP NOT NULL, 
		"ALTER_TIME" TIMESTAMP NOT NULL, 
		"ENABLED" CHAR(1) NOT NULL, 
		"CONTEXT_DESC" BLOB(65536) INLINE LENGTH 116, 
		"AUDITPOLICYID" INTEGER, 
		"AUDITEXCEPTIONENABLED" CHAR(1) NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSCONTROLS" (
		"CONTROLSCHEMA" VARCHAR(128) NOT NULL, 
		"CONTROLNAME" VARCHAR(128) NOT NULL, 
		"OWNER" VARCHAR(128) NOT NULL, 
		"OWNERTYPE" CHAR(1) NOT NULL, 
		"TABSCHEMA" VARCHAR(128) NOT NULL, 
		"TABNAME" VARCHAR(128) NOT NULL, 
		"COLNAME" VARCHAR(128) NOT NULL, 
		"CONTROLID" INTEGER NOT NULL, 
		"CONTROLTYPE" CHAR(1) NOT NULL, 
		"ENFORCED" CHAR(1) NOT NULL, 
		"IMPLICIT" CHAR(1) NOT NULL, 
		"ENABLE" CHAR(1) NOT NULL, 
		"RULETEXT" CLOB(2097152) INLINE LENGTH 164 NOT NULL, 
		"TABCORRELATION" VARCHAR(128) NOT NULL, 
		"PACKED_DESC" BLOB(3145728) INLINE LENGTH 164 NOT NULL, 
		"CREATE_TIME" TIMESTAMP NOT NULL, 
		"ALTER_TIME" TIMESTAMP NOT NULL, 
		"VALID" CHAR(1) NOT NULL, 
		"QUALIFIER" VARCHAR(128) NOT NULL, 
		"FUNC_PATH" CLOB(2048) INLINE LENGTH 92 NOT NULL, 
		"COLLATIONID" CHAR (8) FOR BIT DATA NOT NULL, 
		"COLLATIONID_ORDERBY" CHAR (8) FOR BIT DATA NOT NULL, 
		"STRINGUNITS" CHAR(1) NOT NULL, 
		"ENVID" INTEGER NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSDATAPARTITIONEXPRESSION" (
		"TABSCHEMA" VARCHAR(128) NOT NULL, 
		"TABNAME" VARCHAR(128) NOT NULL, 
		"DATAPARTITIONKEYSEQ" INTEGER NOT NULL, 
		"DATAPARTITIONEXPRESSION" CLOB(32768) INLINE LENGTH 116 NOT NULL, 
		"NULLSFIRST" CHAR(1) NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSDATAPARTITIONS" (
		"DATAPARTITIONNAME" VARCHAR(128) NOT NULL, 
		"TABSCHEMA" VARCHAR(128) NOT NULL, 
		"TABNAME" VARCHAR(128) NOT NULL, 
		"DATAPARTITIONID" INTEGER NOT NULL, 
		"TBSPACEID" INTEGER, 
		"PARTITIONOBJECTID" INTEGER, 
		"LONG_TBSPACEID" INTEGER, 
		"ACCESS_MODE" CHAR(1) NOT NULL, 
		"STATUS" VARCHAR(32) NOT NULL, 
		"SEQNO" INTEGER NOT NULL, 
		"LOWINCLUSIVE" CHAR(1) NOT NULL, 
		"LOWVALUE" VARCHAR(512) NOT NULL, 
		"HIGHINCLUSIVE" CHAR(1) NOT NULL, 
		"HIGHVALUE" VARCHAR(512) NOT NULL, 
		"ROWFORMATVERSION" SMALLINT NOT NULL, 
		"CARD" BIGINT NOT NULL, 
		"OVERFLOW" BIGINT NOT NULL, 
		"NPAGES" BIGINT NOT NULL, 
		"FPAGES" BIGINT NOT NULL, 
		"ACTIVE_BLOCKS" BIGINT NOT NULL, 
		"INDEX_TBSPACEID" INTEGER NOT NULL, 
		"AVGROWSIZE" SMALLINT NOT NULL, 
		"PCTROWSCOMPRESSED" REAL NOT NULL, 
		"PCTPAGESAVED" SMALLINT NOT NULL, 
		"AVGCOMPRESSEDROWSIZE" SMALLINT NOT NULL, 
		"AVGROWCOMPRESSIONRATIO" REAL NOT NULL, 
		"STATS_TIME" TIMESTAMP, 
		"LASTUSED" DATE NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSDATATYPES" (
		"NAME" VARCHAR(128) NOT NULL, 
		"SCHEMA" VARCHAR(128) NOT NULL, 
		"DEFINER" VARCHAR(128) NOT NULL, 
		"SOURCETYPE" VARCHAR(128), 
		"SOURCESCHEMA" VARCHAR(128), 
		"METATYPE" CHAR(1) NOT NULL, 
		"TYPEID" SMALLINT NOT NULL, 
		"SOURCETYPEID" SMALLINT, 
		"LENGTH" INTEGER NOT NULL, 
		"SCALE" SMALLINT NOT NULL, 
		"CODEPAGE" SMALLINT NOT NULL, 
		"CREATE_TIME" TIMESTAMP NOT NULL, 
		"REMARKS" VARCHAR(254), 
		"PACKED_DESC" BLOB(2097152) INLINE LENGTH 164, 
		"TYPE_DESC" BLOB(1048576) INLINE LENGTH 164, 
		"ATTRCOUNT" SMALLINT NOT NULL, 
		"INSTANTIABLE" CHAR(1) NOT NULL, 
		"WITH_FUNC_ACCESS" CHAR(1) NOT NULL, 
		"FINAL" CHAR(1) NOT NULL, 
		"INLINE_LENGTH" INTEGER NOT NULL, 
		"JARSCHEMA" VARCHAR(128), 
		"JAR_ID" VARCHAR(128), 
		"CLASS" VARCHAR(384), 
		"SQLJ_REPRESENTATION" CHAR(1), 
		"NATURAL_INLINE_LENGTH" INTEGER, 
		"ALTER_TIME" TIMESTAMP NOT NULL, 
		"DEFINERTYPE" CHAR(1) NOT NULL, 
		"ARRAY_LENGTH" INTEGER, 
		"COLLATIONID" CHAR (8) FOR BIT DATA, 
		"TYPEMODULEID" INTEGER, 
		"PUBLISHED" CHAR(1) NOT NULL, 
		"SOURCEMODULEID" INTEGER, 
		"VALID" CHAR(1) NOT NULL, 
		"ARRAYINDEXTYPEID" SMALLINT, 
		"NULLS" CHAR(1) NOT NULL, 
		"FUNC_PATH" CLOB(2048) INLINE LENGTH 92, 
		"CONSTRAINT_TEXT" CLOB(65536) INLINE LENGTH 116, 
		"STRINGUNITS" CHAR(1) NOT NULL, 
		"ARRAYINDEXTYPESCALE" SMALLINT, 
		"ENVID" INTEGER NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSDBAUTH" (
		"GRANTOR" VARCHAR(128) NOT NULL, 
		"GRANTEE" VARCHAR(128) NOT NULL, 
		"DBADMAUTH" CHAR(1) NOT NULL, 
		"CREATETABAUTH" CHAR(1) NOT NULL, 
		"BINDADDAUTH" CHAR(1) NOT NULL, 
		"CONNECTAUTH" CHAR(1) NOT NULL, 
		"NOFENCEAUTH" CHAR(1) NOT NULL, 
		"GRANTEETYPE" CHAR(1) NOT NULL, 
		"IMPLSCHEMAAUTH" CHAR(1) NOT NULL, 
		"LOADAUTH" CHAR(1) NOT NULL, 
		"EXTERNALROUTINEAUTH" CHAR(1) NOT NULL, 
		"QUIESCECONNECTAUTH" CHAR(1) NOT NULL, 
		"SECURITYADMAUTH" CHAR(1) NOT NULL, 
		"LIBRARYADMAUTH" CHAR(1) NOT NULL, 
		"GRANTORTYPE" CHAR(1) NOT NULL, 
		"GRANTEEROLEID" INTEGER, 
		"GRANTORROLEID" INTEGER, 
		"SQLADMAUTH" CHAR(1) NOT NULL, 
		"WLMADMAUTH" CHAR(1) NOT NULL, 
		"EXPLAINAUTH" CHAR(1) NOT NULL, 
		"DATAACCESSAUTH" CHAR(1) NOT NULL, 
		"ACCESSCTRLAUTH" CHAR(1) NOT NULL, 
		"CREATESECUREAUTH" CHAR(1) NOT NULL, 
		"REFRESHAUTH" CHAR(1) NOT NULL, 
		"DEBUGAUTH" CHAR(1) NOT NULL, 
		"AUTH25" CHAR(1) NOT NULL, 
		"AUTH26" CHAR(1) NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSDEPENDENCIES" (
		"BNAME" VARCHAR(128) NOT NULL, 
		"BSCHEMA" VARCHAR(128) NOT NULL, 
		"BTYPE" CHAR(1) NOT NULL, 
		"DNAME" VARCHAR(128) NOT NULL, 
		"DSCHEMA" VARCHAR(128) NOT NULL, 
		"TABAUTH" SMALLINT, 
		"DTYPE" CHAR(1) NOT NULL, 
		"BUNIQUE_ID" CHAR (8) FOR BIT DATA, 
		"DOWNER" VARCHAR(128) NOT NULL, 
		"DOWNERTYPE" CHAR(1) NOT NULL, 
		"BMODULEID" INTEGER, 
		"DMODULEID" INTEGER
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSENVIRONMENT" (
		"ENVID" INTEGER NOT NULL, 
		"HASH" INTEGER NOT NULL, 
		"REFCOUNT" INTEGER NOT NULL, 
		"DATETIMELOCALE" CLOB(128) INLINE LENGTH 68, 
		"TIMESTAMPFORMAT" CLOB(254) INLINE LENGTH 68, 
		"DATEFORMAT" CLOB(254) INLINE LENGTH 68, 
		"TIMEFORMAT" CLOB(254) INLINE LENGTH 68, 
		"PROPERTIES" VARCHAR(64), 
		"PACKED_DESC" BLOB(65536) INLINE LENGTH 116 NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSEVENTMONITORS" (
		"NAME" VARCHAR(128) NOT NULL, 
		"DEFINER" VARCHAR(128) NOT NULL, 
		"TARGET_TYPE" CHAR(1) NOT NULL, 
		"TARGET" VARCHAR(762) NOT NULL, 
		"MAXFILES" INTEGER, 
		"MAXFILESIZE" INTEGER, 
		"BUFFERSIZE" INTEGER, 
		"IO_MODE" CHAR(1), 
		"WRITE_MODE" CHAR(1), 
		"AUTOSTART" CHAR(1) NOT NULL, 
		"REMARKS" VARCHAR(254), 
		"PACKED_DESC" BLOB(65536) INLINE LENGTH 116 NOT NULL, 
		"NODENUM" SMALLINT NOT NULL, 
		"MONSCOPE" CHAR(1) NOT NULL, 
		"EVMON_ACTIVATES" INTEGER NOT NULL, 
		"DEFINERTYPE" CHAR(1) NOT NULL, 
		"EVMONID" INTEGER NOT NULL, 
		"VERSIONNUMBER" INTEGER NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSEVENTS" (
		"NAME" VARCHAR(128) NOT NULL, 
		"TYPE" VARCHAR(128) NOT NULL, 
		"FILTER" CLOB(65536) INLINE LENGTH 116
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSEVENTTABLES" (
		"EVMONNAME" VARCHAR(128) NOT NULL, 
		"LOGICAL_GROUP" VARCHAR(128) NOT NULL, 
		"TABNAME" VARCHAR(128) NOT NULL, 
		"TABSCHEMA" VARCHAR(128) NOT NULL, 
		"PCTDEACTIVATE" SMALLINT NOT NULL, 
		"TABOPTIONS" VARCHAR(32) NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSFUNCMAPOPTIONS" (
		"FUNCTION_MAPPING" VARCHAR(128) NOT NULL, 
		"OPTION" VARCHAR(128) NOT NULL, 
		"SETTING" VARCHAR(2048) NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSFUNCMAPPARMOPTIONS" (
		"FUNCTION_MAPPING" VARCHAR(128) NOT NULL, 
		"ORDINAL" SMALLINT NOT NULL, 
		"LOCATION" CHAR(1) NOT NULL, 
		"OPTION" VARCHAR(128) NOT NULL, 
		"SETTING" VARCHAR(2048) NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSFUNCMAPPINGS" (
		"FUNCTION_MAPPING" VARCHAR(128) NOT NULL, 
		"FUNCSCHEMA" VARCHAR(128), 
		"FUNCNAME" VARCHAR(1024), 
		"FUNCID" INTEGER, 
		"SPECIFICNAME" VARCHAR(128), 
		"DEFINER" VARCHAR(128) NOT NULL, 
		"SERVERNAME" VARCHAR(128), 
		"SERVERTYPE" VARCHAR(30), 
		"SERVERVERSION" VARCHAR(18), 
		"WRAPNAME" VARCHAR(128), 
		"CREATE_TIME" TIMESTAMP NOT NULL, 
		"REMARKS" VARCHAR(254), 
		"DEFINERTYPE" CHAR(1) NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSHIERARCHIES" (
		"METATYPE" CHAR(1) NOT NULL, 
		"SUB_SCHEMA" VARCHAR(128) NOT NULL, 
		"SUB_NAME" VARCHAR(128) NOT NULL, 
		"SUPER_SCHEMA" VARCHAR(128) NOT NULL, 
		"SUPER_NAME" VARCHAR(128) NOT NULL, 
		"ROOT_SCHEMA" VARCHAR(128) NOT NULL, 
		"ROOT_NAME" VARCHAR(128) NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSHISTOGRAMTEMPLATEBINS" (
		"TEMPLATEID" INTEGER NOT NULL, 
		"BINID" INTEGER NOT NULL, 
		"BINUPPERVALUE" BIGINT NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSHISTOGRAMTEMPLATES" (
		"TEMPLATEID" INTEGER NOT NULL, 
		"TEMPLATENAME" VARCHAR(128) NOT NULL, 
		"CREATE_TIME" TIMESTAMP NOT NULL, 
		"ALTER_TIME" TIMESTAMP NOT NULL, 
		"NUMBINS" INTEGER NOT NULL, 
		"TEMPLATE_DESC" BLOB(8192) INLINE LENGTH 92
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSHISTOGRAMTEMPLATEUSE" (
		"TEMPLATEID" INTEGER NOT NULL, 
		"HISTOGRAMTYPE" CHAR(1) NOT NULL, 
		"OBJECTTYPE" CHAR(1) NOT NULL, 
		"OBJECTID" INTEGER NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSINDEXAUTH" (
		"GRANTOR" VARCHAR(128) NOT NULL, 
		"GRANTEE" VARCHAR(128) NOT NULL, 
		"NAME" VARCHAR(128) NOT NULL, 
		"CREATOR" VARCHAR(128) NOT NULL, 
		"CONTROLAUTH" CHAR(1) NOT NULL, 
		"GRANTEETYPE" CHAR(1) NOT NULL, 
		"GRANTORTYPE" CHAR(1) NOT NULL, 
		"GRANTEEROLEID" INTEGER, 
		"GRANTORROLEID" INTEGER
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSINDEXCOLUSE" (
		"INDSCHEMA" VARCHAR(128) NOT NULL, 
		"INDNAME" VARCHAR(128) NOT NULL, 
		"COLNAME" VARCHAR(128) NOT NULL, 
		"COLSEQ" SMALLINT NOT NULL, 
		"COLORDER" CHAR(1) NOT NULL, 
		"COLLATIONID" CHAR (8) FOR BIT DATA, 
		"TEXT" CLOB(65536) INLINE LENGTH 116
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSINDEXES" (
		"NAME" VARCHAR(128) NOT NULL, 
		"CREATOR" VARCHAR(128) NOT NULL, 
		"TBNAME" VARCHAR(128) NOT NULL, 
		"TBCREATOR" VARCHAR(128) NOT NULL, 
		"COLNAMES" VARCHAR(640) NOT NULL, 
		"UNIQUERULE" CHAR(1) NOT NULL, 
		"COLCOUNT" SMALLINT NOT NULL, 
		"IID" SMALLINT NOT NULL, 
		"NLEAF" BIGINT NOT NULL, 
		"NLEVELS" SMALLINT NOT NULL, 
		"FIRSTKEYCARD" BIGINT NOT NULL, 
		"FULLKEYCARD" BIGINT NOT NULL, 
		"CLUSTERRATIO" SMALLINT NOT NULL, 
		"CLUSTERFACTOR" DOUBLE NOT NULL, 
		"USER_DEFINED" SMALLINT NOT NULL, 
		"SYSTEM_REQUIRED" SMALLINT NOT NULL, 
		"CREATE_TIME" TIMESTAMP NOT NULL, 
		"STATS_TIME" TIMESTAMP, 
		"PAGE_FETCH_PAIRS" VARCHAR(520) NOT NULL, 
		"REMARKS" VARCHAR(254), 
		"DEFINER" VARCHAR(128) NOT NULL, 
		"MADE_UNIQUE" CHAR(1) NOT NULL, 
		"SEQUENTIAL_PAGES" BIGINT NOT NULL, 
		"DENSITY" INTEGER NOT NULL, 
		"FIRST2KEYCARD" BIGINT NOT NULL, 
		"FIRST3KEYCARD" BIGINT NOT NULL, 
		"FIRST4KEYCARD" BIGINT NOT NULL, 
		"PCTFREE" SMALLINT NOT NULL, 
		"UNIQUE_COLCOUNT" SMALLINT NOT NULL, 
		"INDEXTYPE" CHAR(4) NOT NULL, 
		"ENTRYTYPE" CHAR(1) NOT NULL, 
		"MINPCTUSED" SMALLINT NOT NULL, 
		"REVERSE_SCANS" CHAR(1) NOT NULL, 
		"IESCHEMA" VARCHAR(128), 
		"IENAME" VARCHAR(128), 
		"IEARGUMENTS" CLOB(65536) INLINE LENGTH 116, 
		"INDEX_DESC" BLOB(1048576) INLINE LENGTH 164, 
		"INTERNAL_FORMAT" SMALLINT NOT NULL, 
		"INDEX_OBJECTID" INTEGER NOT NULL, 
		"TBSPACEID" INTEGER NOT NULL, 
		"AVERAGE_SEQUENCE_GAP" DOUBLE NOT NULL, 
		"AVERAGE_SEQUENCE_FETCH_GAP" DOUBLE NOT NULL, 
		"AVERAGE_SEQUENCE_PAGES" DOUBLE NOT NULL, 
		"AVERAGE_SEQUENCE_FETCH_PAGES" DOUBLE NOT NULL, 
		"AVERAGE_RANDOM_PAGES" DOUBLE NOT NULL, 
		"AVERAGE_RANDOM_FETCH_PAGES" DOUBLE NOT NULL, 
		"NUMRIDS" BIGINT NOT NULL, 
		"NUMRIDS_DELETED" BIGINT NOT NULL, 
		"NUM_EMPTY_LEAFS" BIGINT NOT NULL, 
		"OS_PTR_SIZE" INTEGER NOT NULL, 
		"LEVEL2PCTFREE" SMALLINT NOT NULL, 
		"PAGESPLIT" CHAR(1) NOT NULL, 
		"AVGPARTITION_CLUSTERRATIO" SMALLINT NOT NULL, 
		"AVGPARTITION_CLUSTERFACTOR" DOUBLE NOT NULL, 
		"AVGPARTITION_PAGE_FETCH_PAIRS" VARCHAR(520) NOT NULL, 
		"DATAPARTITION_CLUSTERFACTOR" DOUBLE NOT NULL, 
		"INDCARD" BIGINT NOT NULL, 
		"DEFINERTYPE" CHAR(1) NOT NULL, 
		"COLLECTSTATISTICS" CHAR(1) NOT NULL, 
		"COMPRESSION" CHAR(1) NOT NULL, 
		"PCTPAGESSAVED" SMALLINT NOT NULL, 
		"AVGLEAFKEYSIZE" INTEGER NOT NULL, 
		"AVGNLEAFKEYSIZE" INTEGER NOT NULL, 
		"LASTUSED" DATE NOT NULL, 
		"PERIODNAME" VARCHAR(128), 
		"PERIODPOLICY" CHAR(1) NOT NULL, 
		"MADE_WITHOUTOVERLAPS" CHAR(1) NOT NULL, 
		"NULLKEYS" CHAR(1) NOT NULL, 
		"FUNC_PATH" CLOB(2048) INLINE LENGTH 92, 
		"STRINGUNITS" CHAR(1) NOT NULL, 
		"ENVID" INTEGER NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSINDEXEXPLOITRULES" (
		"FUNCID" INTEGER NOT NULL, 
		"SPECID" SMALLINT NOT NULL, 
		"IESCHEMA" VARCHAR(128) NOT NULL, 
		"IENAME" VARCHAR(128) NOT NULL, 
		"RULEID" SMALLINT NOT NULL, 
		"SEARCHMETHODID" SMALLINT NOT NULL, 
		"SEARCHKEY" VARCHAR(640) NOT NULL, 
		"SEARCHARGUMENT" VARCHAR(2700) NOT NULL, 
		"EXACT" CHAR(1) NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSINDEXEXTENSIONMETHODS" (
		"METHODNAME" VARCHAR(128) NOT NULL, 
		"METHODID" SMALLINT NOT NULL, 
		"IESCHEMA" VARCHAR(128) NOT NULL, 
		"IENAME" VARCHAR(128) NOT NULL, 
		"RTFUNCSCHEMA" VARCHAR(128) NOT NULL, 
		"RTFUNCNAME" VARCHAR(128) NOT NULL, 
		"RTSPECIFICNAME" VARCHAR(128) NOT NULL, 
		"CWFUNCSCHEMA" VARCHAR(128), 
		"CWFUNCNAME" VARCHAR(128), 
		"CWSPECIFICNAME" VARCHAR(128), 
		"REMARKS" VARCHAR(254)
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSINDEXEXTENSIONPARMS" (
		"IESCHEMA" VARCHAR(128) NOT NULL, 
		"IENAME" VARCHAR(128) NOT NULL, 
		"ORDINAL" SMALLINT NOT NULL, 
		"PARMNAME" VARCHAR(128) NOT NULL, 
		"TYPESCHEMA" VARCHAR(128) NOT NULL, 
		"TYPENAME" VARCHAR(128) NOT NULL, 
		"LENGTH" INTEGER NOT NULL, 
		"SCALE" SMALLINT NOT NULL, 
		"PARMTYPE" CHAR(1) NOT NULL, 
		"CODEPAGE" SMALLINT NOT NULL, 
		"COLLATIONID" CHAR (8) FOR BIT DATA
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSINDEXEXTENSIONS" (
		"IESCHEMA" VARCHAR(128) NOT NULL, 
		"IENAME" VARCHAR(128) NOT NULL, 
		"DEFINER" VARCHAR(128) NOT NULL, 
		"CREATE_TIME" TIMESTAMP NOT NULL, 
		"KTFUNCSCHEMA" VARCHAR(128) NOT NULL, 
		"KTFUNCNAME" VARCHAR(128) NOT NULL, 
		"KTSPECIFICNAME" VARCHAR(128) NOT NULL, 
		"TEXT" CLOB(2097152) INLINE LENGTH 164 NOT NULL, 
		"INDEX_DESC" BLOB(10485760) INLINE LENGTH 196 NOT NULL, 
		"REMARKS" VARCHAR(254), 
		"DEFINERTYPE" CHAR(1) NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSINDEXOPTIONS" (
		"INDSCHEMA" VARCHAR(128) NOT NULL, 
		"INDNAME" VARCHAR(128) NOT NULL, 
		"OPTION" VARCHAR(128) NOT NULL, 
		"SETTING" VARCHAR(2048) NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSINDEXPARTITIONS" (
		"INDSCHEMA" VARCHAR(128) NOT NULL, 
		"INDNAME" VARCHAR(128) NOT NULL, 
		"TABSCHEMA" VARCHAR(128) NOT NULL, 
		"TABNAME" VARCHAR(128) NOT NULL, 
		"IID" SMALLINT NOT NULL, 
		"INDPARTITIONTBSPACEID" INTEGER NOT NULL, 
		"INDPARTITIONOBJECTID" INTEGER NOT NULL, 
		"DATAPARTITIONID" INTEGER NOT NULL, 
		"INDCARD" BIGINT NOT NULL, 
		"NLEAF" BIGINT NOT NULL, 
		"NUM_EMPTY_LEAFS" BIGINT NOT NULL, 
		"NUMRIDS" BIGINT NOT NULL, 
		"NUMRIDS_DELETED" BIGINT NOT NULL, 
		"FULLKEYCARD" BIGINT NOT NULL, 
		"NLEVELS" SMALLINT NOT NULL, 
		"CLUSTERRATIO" SMALLINT NOT NULL, 
		"CLUSTERFACTOR" DOUBLE NOT NULL, 
		"FIRSTKEYCARD" BIGINT NOT NULL, 
		"FIRST2KEYCARD" BIGINT NOT NULL, 
		"FIRST3KEYCARD" BIGINT NOT NULL, 
		"FIRST4KEYCARD" BIGINT NOT NULL, 
		"AVGLEAFKEYSIZE" INTEGER NOT NULL, 
		"AVGNLEAFKEYSIZE" INTEGER NOT NULL, 
		"PCTFREE" SMALLINT NOT NULL, 
		"PAGE_FETCH_PAIRS" VARCHAR(520) NOT NULL, 
		"SEQUENTIAL_PAGES" BIGINT NOT NULL, 
		"DENSITY" INTEGER NOT NULL, 
		"AVERAGE_SEQUENCE_GAP" DOUBLE NOT NULL, 
		"AVERAGE_SEQUENCE_FETCH_GAP" DOUBLE NOT NULL, 
		"AVERAGE_SEQUENCE_PAGES" DOUBLE NOT NULL, 
		"AVERAGE_SEQUENCE_FETCH_PAGES" DOUBLE NOT NULL, 
		"AVERAGE_RANDOM_PAGES" DOUBLE NOT NULL, 
		"AVERAGE_RANDOM_FETCH_PAGES" DOUBLE NOT NULL, 
		"STATS_TIME" TIMESTAMP, 
		"COMPRESSION" CHAR(1) NOT NULL, 
		"PCTPAGESSAVED" SMALLINT NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSINDEXXMLPATTERNS" (
		"INDSCHEMA" VARCHAR(128) NOT NULL, 
		"INDNAME" VARCHAR(128) NOT NULL, 
		"PINDNAME" VARCHAR(128) NOT NULL, 
		"PINDID" SMALLINT NOT NULL, 
		"TYPEMODEL" CHAR(1) NOT NULL, 
		"DATATYPE" VARCHAR(128) NOT NULL, 
		"HASHED" CHAR(1) NOT NULL, 
		"LENGTH" SMALLINT NOT NULL, 
		"PATTERNID" SMALLINT NOT NULL, 
		"PATTERN" CLOB(2097152) INLINE LENGTH 164, 
		"SCALE" SMALLINT NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSINVALIDOBJECTS" (
		"OBJECTSCHEMA" VARCHAR(128) NOT NULL, 
		"OBJECTNAME" VARCHAR(128) NOT NULL, 
		"OBJECTMODULEID" INTEGER, 
		"OBJECTTYPE" CHAR(1) NOT NULL, 
		"SQLCODE" INTEGER, 
		"SQLSTATE" CHAR(5), 
		"SQLERRMC" VARCHAR(70), 
		"LINENUMBER" INTEGER, 
		"INVALIDATE_TIME" TIMESTAMP NOT NULL, 
		"LAST_REGEN_TIME" TIMESTAMP
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSJARCONTENTS" (
		"JARSCHEMA" VARCHAR(128) NOT NULL, 
		"JAR_ID" VARCHAR(128) NOT NULL, 
		"CLASS" VARCHAR(384) NOT NULL, 
		"CLASS_SOURCE" CLOB(10485760) INLINE LENGTH 196
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSJAROBJECTS" (
		"JARSCHEMA" VARCHAR(128) NOT NULL, 
		"JAR_ID" VARCHAR(128) NOT NULL, 
		"DEFINER" VARCHAR(128) NOT NULL, 
		"JAR_DATA" BLOB(104857600) INLINE LENGTH 196, 
		"ALTEREDTS" TIMESTAMP NOT NULL, 
		"CREATEDTS" TIMESTAMP NOT NULL, 
		"DEFINERTYPE" CHAR(1) NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSJOBS" (
		"JOBID" BIGINT NOT NULL, 
		"JOBTYPE" INTEGER NOT NULL, 
		"JOBVERSION" INTEGER NOT NULL, 
		"NUMSTAGES" INTEGER NOT NULL, 
		"STAGESYNC" CHAR (8) FOR BIT DATA NOT NULL, 
		"CREATE_TIME" TIMESTAMP NOT NULL, 
		"CREATE_DBPARTITIONNUM" SMALLINT NOT NULL, 
		"OWNER" VARCHAR(128) NOT NULL, 
		"PRIORITY" INTEGER, 
		"STATE" CHAR(1), 
		"JOB_DESC" BLOB(4190000) INLINE LENGTH 164, 
		"OWNERTYPE" CHAR(1) NOT NULL, 
		"CREATE_MEMBER" SMALLINT NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSKEYCOLUSE" (
		"CONSTNAME" VARCHAR(128) NOT NULL, 
		"TBNAME" VARCHAR(128) NOT NULL, 
		"TBCREATOR" VARCHAR(128) NOT NULL, 
		"COLNAME" VARCHAR(128) NOT NULL, 
		"COLSEQ" SMALLINT NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSLIBRARIES" (
		"LIBSCHEMA" VARCHAR(128) NOT NULL, 
		"LIBNAME" VARCHAR(128) NOT NULL, 
		"DEFINER" VARCHAR(128) NOT NULL, 
		"LIB_ID" INTEGER NOT NULL, 
		"LIBVERSION_COUNT" INTEGER NOT NULL, 
		"ACTIVE_VERSION" INTEGER NOT NULL, 
		"SYSTEM_REQUIRED" SMALLINT NOT NULL, 
		"DEFINERTYPE" CHAR(1) NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSLIBRARYAUTH" (
		"GRANTOR" VARCHAR(128) NOT NULL, 
		"GRANTEE" VARCHAR(128) NOT NULL, 
		"GRANTEETYPE" CHAR(1) NOT NULL, 
		"LIBSCHEMA" VARCHAR(128) NOT NULL, 
		"LIBNAME" VARCHAR(128) NOT NULL, 
		"USAGEAUTH" CHAR(1) NOT NULL, 
		"ALTERAUTH" CHAR(1) NOT NULL, 
		"GRANTORTYPE" CHAR(1) NOT NULL, 
		"GRANTEEROLEID" INTEGER, 
		"GRANTORROLEID" INTEGER
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSLIBRARYBINDFILES" (
		"LIB_ID" INTEGER NOT NULL, 
		"LIBVERSION" INTEGER NOT NULL, 
		"PACKAGE_SCHEMA" VARCHAR(128) NOT NULL, 
		"PACKAGE_NAME" VARCHAR(128) NOT NULL, 
		"PACKAGE_VERSION" VARCHAR(64) NOT NULL, 
		"BINDFILE_PATH" VARCHAR(255) NOT NULL, 
		"BINDFILE_BODY" BLOB(10485760) INLINE LENGTH 196 NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSLIBRARYVERSIONS" (
		"LIB_ID" INTEGER NOT NULL, 
		"LIBVERSION" INTEGER NOT NULL, 
		"DEFINER" VARCHAR(128) NOT NULL, 
		"CREATE_TIME" TIMESTAMP NOT NULL, 
		"VERSION_PATH" VARCHAR(255) NOT NULL, 
		"BINDFILES_COUNT" SMALLINT NOT NULL, 
		"VERSION_BODY" BLOB(20971520) INLINE LENGTH 196 NOT NULL, 
		"CHECKSUM" INTEGER NOT NULL, 
		"STALE" CHAR(1), 
		"DEFINERTYPE" CHAR(1) NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSMEMBERSUBSETATTRS" (
		"SUBSETID" INTEGER NOT NULL, 
		"ATTRID" SMALLINT NOT NULL, 
		"ATTRVALUE" VARCHAR(1000)
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSMEMBERSUBSETMEMBERS" (
		"SUBSETID" INTEGER NOT NULL, 
		"MEMBER" SMALLINT NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSMEMBERSUBSETS" (
		"SUBSETNAME" VARCHAR(128) NOT NULL, 
		"SUBSETID" INTEGER NOT NULL, 
		"CREATE_TIME" TIMESTAMP NOT NULL, 
		"ALTER_TIME" TIMESTAMP NOT NULL, 
		"ENABLED" CHAR(1) NOT NULL, 
		"SUBSETDESC" BLOB(65536) INLINE LENGTH 116, 
		"MEMBERPRIORITYBASIS" CHAR(1) NOT NULL, 
		"INCLUSIVESUBSET" CHAR(1) NOT NULL, 
		"ALTERNATESERVER" CHAR(1) NOT NULL, 
		"CATALOGDATABASEALIAS" CHAR(1) NOT NULL, 
		"REMARKS" VARCHAR(254)
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSMODULEAUTH" (
		"GRANTOR" VARCHAR(128) NOT NULL, 
		"GRANTORTYPE" CHAR(1) NOT NULL, 
		"GRANTORROLEID" INTEGER, 
		"GRANTEE" VARCHAR(128) NOT NULL, 
		"GRANTEETYPE" CHAR(1) NOT NULL, 
		"GRANTEEROLEID" INTEGER, 
		"MODULEID" INTEGER NOT NULL, 
		"EXECUTEAUTH" CHAR(1) NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSMODULES" (
		"MODULESCHEMA" VARCHAR(128) NOT NULL, 
		"MODULENAME" VARCHAR(128) NOT NULL, 
		"MODULEID" INTEGER NOT NULL, 
		"OWNER" VARCHAR(128) NOT NULL, 
		"OWNERTYPE" CHAR(1) NOT NULL, 
		"MODULETYPE" CHAR(1) NOT NULL, 
		"BASE_MODULESCHEMA" VARCHAR(128), 
		"BASE_MODULENAME" VARCHAR(128), 
		"CREATE_TIME" TIMESTAMP NOT NULL, 
		"SOURCEHEADER" CLOB(2097152) INLINE LENGTH 164 NOT NULL, 
		"SOURCEBODY" CLOB(2097152) INLINE LENGTH 164 NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSNAMEMAPPINGS" (
		"TYPE" CHAR(1) NOT NULL, 
		"LOGICAL_SCHEMA" VARCHAR(128) NOT NULL, 
		"LOGICAL_NAME" VARCHAR(128) NOT NULL, 
		"LOGICAL_COLNAME" VARCHAR(128), 
		"IMPL_SCHEMA" VARCHAR(128) NOT NULL, 
		"IMPL_NAME" VARCHAR(128) NOT NULL, 
		"IMPL_COLNAME" VARCHAR(128)
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSNODEGROUPDEF" (
		"NGNAME" VARCHAR(128) NOT NULL, 
		"NODENUM" SMALLINT NOT NULL, 
		"IN_USE" CHAR(1) NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSNODEGROUPS" (
		"NAME" VARCHAR(128) NOT NULL, 
		"DEFINER" VARCHAR(128) NOT NULL, 
		"PMAP_ID" SMALLINT NOT NULL, 
		"REBALANCE_PMAP_ID" SMALLINT NOT NULL, 
		"CTIME" TIMESTAMP NOT NULL, 
		"REMARKS" VARCHAR(254), 
		"DEFINERTYPE" CHAR(1) NOT NULL, 
		"EXEC_INFO" BLOB(1048576) INLINE LENGTH 164
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSPARTITIONMAPS" (
		"PMAP_ID" SMALLINT NOT NULL, 
		"PARTITIONMAP" BLOB(65536) INLINE LENGTH 116 NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSPASSTHRUAUTH" (
		"GRANTOR" VARCHAR(128) NOT NULL, 
		"GRANTEE" VARCHAR(128) NOT NULL, 
		"GRANTEETYPE" CHAR(1) NOT NULL, 
		"SERVERNAME" VARCHAR(128) NOT NULL, 
		"GRANTORTYPE" CHAR(1) NOT NULL, 
		"GRANTEEROLEID" INTEGER, 
		"GRANTORROLEID" INTEGER
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSPERIODS" (
		"PERIODNAME" VARCHAR(128) NOT NULL, 
		"TABSCHEMA" VARCHAR(128) NOT NULL, 
		"TABNAME" VARCHAR(128) NOT NULL, 
		"FID" SMALLINT NOT NULL, 
		"TID" SMALLINT NOT NULL, 
		"BEGINCOLNO" SMALLINT NOT NULL, 
		"ENDCOLNO" SMALLINT NOT NULL, 
		"PERIODTYPE" SMALLINT NOT NULL, 
		"HISTORYFID" SMALLINT, 
		"HISTORYTID" SMALLINT, 
		"VERSIONING_TIME" TIMESTAMP
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSPLAN" (
		"NAME" VARCHAR(128) NOT NULL, 
		"CREATOR" VARCHAR(128) NOT NULL, 
		"BOUNDBY" VARCHAR(128) NOT NULL, 
		"VALID" CHAR(1) NOT NULL, 
		"UNIQUE_ID" CHAR (8) FOR BIT DATA NOT NULL, 
		"TOTALSECT" SMALLINT NOT NULL, 
		"FORMAT" CHAR(1) NOT NULL, 
		"SECT_INFO" BLOB(1048576) INLINE LENGTH 164 NOT NULL, 
		"HOST_VARS" BLOB(1048576) INLINE LENGTH 164, 
		"ISOLATION" CHAR(2), 
		"BLOCK" CHAR(1), 
		"STANDARDS_LEVEL" CHAR(1), 
		"FUNC_PATH" CLOB(2048) INLINE LENGTH 92 NOT NULL, 
		"EXPLICIT_BIND_TIME" TIMESTAMP NOT NULL, 
		"LAST_BIND_TIME" TIMESTAMP NOT NULL, 
		"QUERYOPT" INTEGER NOT NULL, 
		"EXPLAIN_LEVEL" CHAR(1) NOT NULL, 
		"EXPLAIN_MODE" CHAR(1) NOT NULL, 
		"EXPLAIN_SNAPSHOT" CHAR(1) NOT NULL, 
		"SQLWARN" CHAR(1) NOT NULL, 
		"CODEPAGE" SMALLINT NOT NULL, 
		"REMARKS" VARCHAR(254), 
		"SQLRULES" CHAR(1) NOT NULL, 
		"SQLRULES_STRING" VARCHAR(254) NOT NULL, 
		"INSERT_BUF" CHAR(1) NOT NULL, 
		"DEFINER" VARCHAR(128) NOT NULL, 
		"DEFAULT_SCHEMA" VARCHAR(128) NOT NULL, 
		"MULTINODE_PLANS" CHAR(1) NOT NULL, 
		"DEGREE" CHAR(5) NOT NULL, 
		"RDS_LEVEL" SMALLINT NOT NULL, 
		"SQLMATHWARN" CHAR(1) NOT NULL, 
		"INTRA_PARALLEL" CHAR(1) NOT NULL, 
		"VALIDATE" CHAR(1) NOT NULL, 
		"DYNAMICRULES" CHAR(1) NOT NULL, 
		"SQLERROR" CHAR(1) NOT NULL, 
		"REFRESHAGE" DECIMAL(20 , 6) NOT NULL, 
		"PKG_CREATE_TIME" TIMESTAMP NOT NULL, 
		"FEDERATED" CHAR(1) NOT NULL, 
		"TRANSFORMGROUP" VARCHAR(1024), 
		"TRF_GRP_PACKED_DESC" BLOB(2048) INLINE LENGTH 92, 
		"PKGVERSION" VARCHAR(64) NOT NULL, 
		"REOPTVAR" CHAR(1) NOT NULL, 
		"OS_PTR_SIZE" INTEGER NOT NULL, 
		"PACKED_DESC" BLOB(1048576) INLINE LENGTH 164, 
		"STATICREADONLY" CHAR(1) NOT NULL, 
		"FEDERATED_ASYNCHRONY" INTEGER NOT NULL, 
		"DEFINERTYPE" CHAR(1) NOT NULL, 
		"BOUNDBYTYPE" CHAR(1) NOT NULL, 
		"OPTPROFILESCHEMA" VARCHAR(128), 
		"OPTPROFILENAME" VARCHAR(128), 
		"COLLATIONID" CHAR (8) FOR BIT DATA NOT NULL, 
		"COLLATIONID_ORDERBY" CHAR (8) FOR BIT DATA NOT NULL, 
		"CONCURRENTACCESSRESOLUTION" CHAR(1), 
		"PKGID" BIGINT NOT NULL, 
		"DBPARTITIONNUM" SMALLINT NOT NULL, 
		"APREUSE" CHAR(1) NOT NULL, 
		"ALTER_TIME" TIMESTAMP NOT NULL, 
		"ANONBLOCK" CHAR(1) NOT NULL, 
		"EXTENDEDINDICATOR" CHAR(1) NOT NULL, 
		"LASTUSED" DATE NOT NULL, 
		"BUSTIMESENSITIVE" CHAR(1) NOT NULL, 
		"SYSTIMESENSITIVE" CHAR(1) NOT NULL, 
		"SECTIONLEVEL" BIGINT NOT NULL, 
		"KEEPDYNAMIC" CHAR(1) NOT NULL, 
		"SQLCOMPILEOPTIONS" VARCHAR(32) NOT NULL, 
		"STATICASDYNAMIC" CHAR(1) NOT NULL, 
		"MEMBER" SMALLINT NOT NULL, 
		"STRINGUNITS" CHAR(1) NOT NULL, 
		"ENVID" INTEGER NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSPLANAUTH" (
		"GRANTOR" VARCHAR(128) NOT NULL, 
		"GRANTEE" VARCHAR(128) NOT NULL, 
		"NAME" VARCHAR(128) NOT NULL, 
		"CREATOR" VARCHAR(128) NOT NULL, 
		"CONTROLAUTH" CHAR(1) NOT NULL, 
		"BINDAUTH" CHAR(1) NOT NULL, 
		"EXECUTEAUTH" CHAR(1) NOT NULL, 
		"GRANTEETYPE" CHAR(1) NOT NULL, 
		"GRANTORTYPE" CHAR(1) NOT NULL, 
		"GRANTEEROLEID" INTEGER, 
		"GRANTORROLEID" INTEGER
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSPLANDEP" (
		"BNAME" VARCHAR(128) NOT NULL, 
		"BCREATOR" VARCHAR(128) NOT NULL, 
		"BTYPE" CHAR(1) NOT NULL, 
		"DNAME" VARCHAR(128) NOT NULL, 
		"DCREATOR" VARCHAR(128) NOT NULL, 
		"BINDER" VARCHAR(128) NOT NULL, 
		"TABAUTH" SMALLINT, 
		"TABUSAGE" SMALLINT NOT NULL, 
		"COLUSAGE" BLOB(5120) INLINE LENGTH 92, 
		"DUNIQUE_ID" CHAR (8) FOR BIT DATA NOT NULL, 
		"BINDERTYPE" CHAR(1) NOT NULL, 
		"BMODULEID" INTEGER
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSPREDICATESPECS" (
		"FUNCID" INTEGER NOT NULL, 
		"SPECID" SMALLINT NOT NULL, 
		"CONTEXTOP" CHAR(8) NOT NULL, 
		"CONTEXTEXP" CLOB(2097152) INLINE LENGTH 164 NOT NULL, 
		"FILTERTEXT" CLOB(2097152) INLINE LENGTH 164
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSRELS" (
		"CREATOR" VARCHAR(128) NOT NULL, 
		"TBNAME" VARCHAR(128) NOT NULL, 
		"RELNAME" VARCHAR(128) NOT NULL, 
		"REFTBNAME" VARCHAR(128) NOT NULL, 
		"REFTBCREATOR" VARCHAR(128) NOT NULL, 
		"COLCOUNT" SMALLINT NOT NULL, 
		"DELETERULE" CHAR(1) NOT NULL, 
		"UPDATERULE" CHAR(1) NOT NULL, 
		"TIMESTAMP" TIMESTAMP NOT NULL, 
		"FKCOLNAMES" VARCHAR(640) NOT NULL, 
		"PKCOLNAMES" VARCHAR(640) NOT NULL, 
		"REFKEYNAME" VARCHAR(128) NOT NULL, 
		"DEFINER" VARCHAR(128) NOT NULL, 
		"DEFINERTYPE" CHAR(1) NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSROLEAUTH" (
		"GRANTOR" VARCHAR(128) NOT NULL, 
		"GRANTORTYPE" CHAR(1) NOT NULL, 
		"GRANTORROLEID" INTEGER, 
		"GRANTEE" VARCHAR(128) NOT NULL, 
		"GRANTEETYPE" CHAR(1) NOT NULL, 
		"GRANTEEROLEID" INTEGER, 
		"ROLENAME" VARCHAR(128) NOT NULL, 
		"ROLEID" INTEGER NOT NULL, 
		"ADMIN" CHAR(1) NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSROLES" (
		"ROLENAME" VARCHAR(128) NOT NULL, 
		"ROLEID" INTEGER NOT NULL, 
		"CREATE_TIME" TIMESTAMP NOT NULL, 
		"AUDITPOLICYID" INTEGER, 
		"AUDITEXCEPTIONENABLED" CHAR(1) NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSROUTINEAUTH" (
		"GRANTOR" VARCHAR(128) NOT NULL, 
		"GRANTEE" VARCHAR(128) NOT NULL, 
		"GRANTEETYPE" CHAR(1) NOT NULL, 
		"SCHEMA" VARCHAR(128) NOT NULL, 
		"SPECIFICNAME" VARCHAR(128), 
		"TYPESCHEMA" VARCHAR(128), 
		"TYPENAME" VARCHAR(128), 
		"ROUTINETYPE" CHAR(1) NOT NULL, 
		"EXECUTEAUTH" CHAR(1) NOT NULL, 
		"GRANT_TIME" TIMESTAMP NOT NULL, 
		"GRANTORTYPE" CHAR(1) NOT NULL, 
		"GRANTEEROLEID" INTEGER, 
		"GRANTORROLEID" INTEGER
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSROUTINEOPTIONS" (
		"ROUTINEID" INTEGER NOT NULL, 
		"OPTION" VARCHAR(128) NOT NULL, 
		"SETTING" VARCHAR(2048) NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSROUTINEPARMOPTIONS" (
		"ROUTINEID" INTEGER NOT NULL, 
		"ORDINAL" SMALLINT NOT NULL, 
		"OPTION" VARCHAR(128) NOT NULL, 
		"SETTING" VARCHAR(2048) NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSROUTINEPARMS" (
		"ROUTINENAME" VARCHAR(128) NOT NULL, 
		"ROUTINESCHEMA" VARCHAR(128) NOT NULL, 
		"SPECIFICNAME" VARCHAR(128) NOT NULL, 
		"ROWTYPE" CHAR(1) NOT NULL, 
		"ORDINAL" SMALLINT NOT NULL, 
		"TYPENAME" VARCHAR(128) NOT NULL, 
		"TYPESCHEMA" VARCHAR(128) NOT NULL, 
		"LENGTH" INTEGER NOT NULL, 
		"SCALE" SMALLINT NOT NULL, 
		"CODEPAGE" SMALLINT NOT NULL, 
		"CAST_FUNCTION_ID" INTEGER, 
		"PARMNAME" VARCHAR(128), 
		"LOCATOR" CHAR(1) NOT NULL, 
		"TARGET_TYPESCHEMA" VARCHAR(128), 
		"TARGET_TYPENAME" VARCHAR(128), 
		"SCOPE_TABSCHEMA" VARCHAR(128), 
		"SCOPE_TABNAME" VARCHAR(128), 
		"TRANSFORM_GRPNAME" VARCHAR(128), 
		"ROUTINE_ID" INTEGER NOT NULL, 
		"ROUTINETYPE" CHAR(1) NOT NULL, 
		"TARGET_TYPEID" SMALLINT, 
		"TYPEID" SMALLINT, 
		"REMARKS" VARCHAR(254), 
		"COLLATIONID" CHAR (8) FOR BIT DATA, 
		"ROUTINEMODULEID" INTEGER, 
		"DEFAULT" CLOB(65536) INLINE LENGTH 116, 
		"TYPEMODULEID" INTEGER, 
		"TARGET_TYPEMODULEID" INTEGER
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSROUTINEPROPERTIES" (
		"ROUTINE_ID" INTEGER NOT NULL, 
		"CLASS" VARCHAR(384), 
		"JAR_ID" VARCHAR(128), 
		"JARSCHEMA" VARCHAR(128), 
		"JAR_SIGNATURE" VARCHAR(2048)
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSROUTINES" (
		"ROUTINENAME" VARCHAR(128) NOT NULL, 
		"ROUTINESCHEMA" VARCHAR(128) NOT NULL, 
		"DEFINER" VARCHAR(128) NOT NULL, 
		"SPECIFICNAME" VARCHAR(128) NOT NULL, 
		"PARM_SIGNATURE" VARCHAR (180) FOR BIT DATA NOT NULL, 
		"ROUTINE_ID" INTEGER NOT NULL, 
		"RETURN_TYPE" SMALLINT NOT NULL, 
		"ORIGIN" CHAR(1) NOT NULL, 
		"FUNCTION_TYPE" CHAR(1) NOT NULL, 
		"CREATEDTS" TIMESTAMP NOT NULL, 
		"PARM_COUNT" SMALLINT NOT NULL, 
		"DETERMINISTIC" CHAR(1) NOT NULL, 
		"EXTERNAL_ACTION" CHAR(1) NOT NULL, 
		"FENCED" CHAR(1) NOT NULL, 
		"NULL_CALL" CHAR(1) NOT NULL, 
		"CAST_FUNCTION" CHAR(1) NOT NULL, 
		"ASSIGN_FUNCTION" CHAR(1) NOT NULL, 
		"SCRATCHPAD" CHAR(1) NOT NULL, 
		"FINAL_CALL" CHAR(1) NOT NULL, 
		"LANGUAGE" CHAR(8) NOT NULL, 
		"IMPLEMENTATION" VARCHAR(762), 
		"SOURCESPECIFIC" VARCHAR(128), 
		"SOURCESCHEMA" VARCHAR(128), 
		"IOS_PER_INVOC" DOUBLE NOT NULL, 
		"INSTS_PER_INVOC" DOUBLE NOT NULL, 
		"IOS_PER_ARGBYTE" DOUBLE NOT NULL, 
		"INSTS_PER_ARGBYTE" DOUBLE NOT NULL, 
		"PERCENT_ARGBYTES" SMALLINT NOT NULL, 
		"INITIAL_IOS" DOUBLE NOT NULL, 
		"INITIAL_INSTS" DOUBLE NOT NULL, 
		"INTERNAL_PREC1" INTEGER NOT NULL, 
		"INTERNAL_PREC2" DOUBLE NOT NULL, 
		"REMARKS" VARCHAR(254), 
		"INTERNAL_DESC" BLOB(20971520) INLINE LENGTH 196 NOT NULL, 
		"PARALLEL" CHAR(1) NOT NULL, 
		"SQL_DATA_ACCESS" CHAR(1) NOT NULL, 
		"DBINFO" CHAR(1) NOT NULL, 
		"RESULT_COLS" SMALLINT NOT NULL, 
		"TEXT" CLOB(2097152) INLINE LENGTH 164, 
		"CARDINALITY" BIGINT NOT NULL, 
		"PARAMETER_STYLE" CHAR(8) NOT NULL, 
		"METHODIMPLEMENTED" CHAR(1) NOT NULL, 
		"METHODEFFECT" CHAR(2) NOT NULL, 
		"FUNC_PATH" CLOB(2048) INLINE LENGTH 92, 
		"TYPE_PRESERVING" CHAR(1) NOT NULL, 
		"WITH_FUNC_ACCESS" CHAR(1) NOT NULL, 
		"SELECTIVITY" DOUBLE NOT NULL, 
		"OVERRIDDEN_METHODID" INTEGER, 
		"SUBJECT_TYPESCHEMA" VARCHAR(128), 
		"SUBJECT_TYPENAME" VARCHAR(128), 
		"QUALIFIER" VARCHAR(128) NOT NULL, 
		"SCRATCHPAD_LENGTH" SMALLINT NOT NULL, 
		"LIB_ID" INTEGER, 
		"SPEC_REG" CHAR(1) NOT NULL, 
		"FEDERATED" CHAR(1) NOT NULL, 
		"ALTEREDTS" TIMESTAMP NOT NULL, 
		"SOURCEROUTINEID" INTEGER, 
		"SUBJECT_TYPEID" SMALLINT, 
		"ROUTINETYPE" CHAR(1) NOT NULL, 
		"THREADSAFE" CHAR(1) NOT NULL, 
		"RESULT_SETS" SMALLINT NOT NULL, 
		"PROGRAM_TYPE" CHAR(1) NOT NULL, 
		"VALID" CHAR(1) NOT NULL, 
		"TEXT_BODY_OFFSET" INTEGER NOT NULL, 
		"COMMIT_ON_RETURN" CHAR(1) NOT NULL, 
		"NAMESPACE" CHAR(1) NOT NULL, 
		"METHODPROPERTY" CHAR(1) NOT NULL, 
		"NEWSAVEPOINTLEVEL" CHAR(1) NOT NULL, 
		"EXECUTION_CONTROL" CHAR(1) NOT NULL, 
		"DEBUG_MODE" CHAR(1) NOT NULL, 
		"CODEPAGE" SMALLINT NOT NULL, 
		"ENCODING_SCHEME" CHAR(1) NOT NULL, 
		"LAST_REGEN_TIME" TIMESTAMP NOT NULL, 
		"INHERITLOCKREQUEST" CHAR(1) NOT NULL, 
		"DEFINERTYPE" CHAR(1) NOT NULL, 
		"COLLATIONID" CHAR (8) FOR BIT DATA NOT NULL, 
		"COLLATIONID_ORDERBY" CHAR (8) FOR BIT DATA NOT NULL, 
		"ROUTINEMODULEID" INTEGER, 
		"PUBLISHED" CHAR(1) NOT NULL, 
		"AUTONOMOUS" CHAR(1) NOT NULL, 
		"DIALECT" CHAR(1) NOT NULL, 
		"SECURE" CHAR(1) NOT NULL, 
		"STRINGUNITS" CHAR(1) NOT NULL, 
		"ENVID" INTEGER NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSSCHEMAAUTH" (
		"GRANTOR" VARCHAR(128) NOT NULL, 
		"GRANTEE" VARCHAR(128) NOT NULL, 
		"GRANTEETYPE" CHAR(1) NOT NULL, 
		"SCHEMANAME" VARCHAR(128) NOT NULL, 
		"CREATEINAUTH" CHAR(1) NOT NULL, 
		"DROPINAUTH" CHAR(1) NOT NULL, 
		"ALTERINAUTH" CHAR(1) NOT NULL, 
		"GRANTORTYPE" CHAR(1) NOT NULL, 
		"GRANTEEROLEID" INTEGER, 
		"GRANTORROLEID" INTEGER
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSSCHEMATA" (
		"NAME" VARCHAR(128) NOT NULL, 
		"OWNER" VARCHAR(128) NOT NULL, 
		"DEFINER" VARCHAR(128) NOT NULL, 
		"CREATE_TIME" TIMESTAMP NOT NULL, 
		"REMARKS" VARCHAR(254), 
		"DEFINERTYPE" CHAR(1) NOT NULL, 
		"OWNERTYPE" CHAR(1) NOT NULL, 
		"DATACAPTURE" CHAR(1) NOT NULL, 
		"AUDITPOLICYID" INTEGER, 
		"AUDITEXCEPTIONENABLED" CHAR(1) NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSSCPREFTBSPACES" (
		"SERVICECLASSID" SMALLINT NOT NULL, 
		"TBSPACEID" INTEGER NOT NULL, 
		"TBSPACEORDER" SMALLINT NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSSECTION" (
		"PLNAME" VARCHAR(128) NOT NULL, 
		"PLCREATOR" VARCHAR(128) NOT NULL, 
		"SECTNO" SMALLINT NOT NULL, 
		"SECTION" BLOB(10485760) INLINE LENGTH 196, 
		"VALID" CHAR(1) NOT NULL, 
		"UNIQUE_ID" CHAR (8) FOR BIT DATA NOT NULL, 
		"SECTION_INFO" BLOB(4190000) INLINE LENGTH 164
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSSECURITYLABELACCESS" (
		"GRANTOR" VARCHAR(128) NOT NULL, 
		"GRANTORTYPE" CHAR(1) NOT NULL, 
		"GRANTEE" VARCHAR(128) NOT NULL, 
		"GRANTEETYPE" CHAR(1) NOT NULL, 
		"SECLABELID" INTEGER NOT NULL, 
		"SECPOLICYID" INTEGER NOT NULL, 
		"ACCESSTYPE" CHAR(1) NOT NULL, 
		"GRANT_TIME" TIMESTAMP NOT NULL, 
		"GRANTEEROLEID" INTEGER, 
		"GRANTORROLEID" INTEGER
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSSECURITYLABELCOMPONENTELEMENTS" (
		"COMPID" INTEGER NOT NULL, 
		"ELEMENTVALUE" VARCHAR(32) NOT NULL, 
		"ELEMENTVALUEENCODING" CHAR (8) FOR BIT DATA NOT NULL, 
		"PARENTELEMENTVALUE" VARCHAR(32)
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSSECURITYLABELCOMPONENTS" (
		"COMPNAME" VARCHAR(128) NOT NULL, 
		"COMPID" INTEGER NOT NULL, 
		"COMPTYPE" CHAR(1) NOT NULL, 
		"NUMELEMENTS" INTEGER NOT NULL, 
		"ENCODINGINFO" VARCHAR (128) FOR BIT DATA, 
		"CREATE_TIME" TIMESTAMP NOT NULL, 
		"ALTER_TIME" TIMESTAMP NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSSECURITYLABELS" (
		"SECLABELNAME" VARCHAR(128) NOT NULL, 
		"SECPOLICYID" INTEGER NOT NULL, 
		"SECLABELID" INTEGER NOT NULL, 
		"SECLABEL_INTERNAL" VARCHAR (128) FOR BIT DATA NOT NULL, 
		"CREATE_TIME" TIMESTAMP NOT NULL, 
		"ALTER_TIME" TIMESTAMP NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSSECURITYPOLICIES" (
		"SECPOLICYNAME" VARCHAR(128) NOT NULL, 
		"SECPOLICYID" INTEGER NOT NULL, 
		"NUMSECLABELCOMP" INTEGER NOT NULL, 
		"RWSECLABELREL" CHAR(1) NOT NULL, 
		"NOTAUTHWRITESECLABEL" CHAR(1) NOT NULL, 
		"CREATE_TIME" TIMESTAMP NOT NULL, 
		"ALTER_TIME" TIMESTAMP NOT NULL, 
		"USERAUTHS" CHAR(1) NOT NULL, 
		"GROUPAUTHS" CHAR(1) NOT NULL, 
		"ROLEAUTHS" CHAR(1) NOT NULL, 
		"PACKED_DESC" BLOB(65536) INLINE LENGTH 116
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSSECURITYPOLICYCOMPONENTRULES" (
		"SECPOLICYID" INTEGER NOT NULL, 
		"COMPID" INTEGER NOT NULL, 
		"ORDINAL" INTEGER NOT NULL, 
		"READACCESSRULENAME" VARCHAR(128) NOT NULL, 
		"READACCESSRULETEXT" VARCHAR(512) NOT NULL, 
		"READACCESSRULE" CHAR (1) FOR BIT DATA NOT NULL, 
		"WRITEACCESSRULENAME" VARCHAR(128) NOT NULL, 
		"WRITEACCESSRULETEXT" VARCHAR(512) NOT NULL, 
		"WRITEACCESSRULE" CHAR (1) FOR BIT DATA NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSSECURITYPOLICYEXEMPTIONS" (
		"GRANTOR" VARCHAR(128) NOT NULL, 
		"GRANTORTYPE" CHAR(1) NOT NULL, 
		"GRANTEE" VARCHAR(128) NOT NULL, 
		"GRANTEETYPE" CHAR(1) NOT NULL, 
		"SECPOLICYID" INTEGER NOT NULL, 
		"ACCESSRULENAME" VARCHAR(128) NOT NULL, 
		"ACCESSTYPE" CHAR(1) NOT NULL, 
		"ORDINAL" INTEGER NOT NULL, 
		"EXEMPTION" CHAR (1) FOR BIT DATA NOT NULL, 
		"ACTIONALLOWED" CHAR(1) NOT NULL, 
		"GRANT_TIME" TIMESTAMP NOT NULL, 
		"GRANTEEROLEID" INTEGER, 
		"GRANTORROLEID" INTEGER
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSSEQUENCEAUTH" (
		"GRANTOR" VARCHAR(128) NOT NULL, 
		"GRANTEE" VARCHAR(128) NOT NULL, 
		"GRANTEETYPE" CHAR(1) NOT NULL, 
		"SEQID" INTEGER NOT NULL, 
		"USAGEAUTH" CHAR(1) NOT NULL, 
		"ALTERAUTH" CHAR(1) NOT NULL, 
		"GRANTORTYPE" CHAR(1) NOT NULL, 
		"GRANTEEROLEID" INTEGER, 
		"GRANTORROLEID" INTEGER
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSSEQUENCES" (
		"LASTASSIGNEDVAL" DECIMAL(31 , 0), 
		"SEQID" INTEGER NOT NULL, 
		"SEQSCHEMA" VARCHAR(128) NOT NULL, 
		"SEQNAME" VARCHAR(128) NOT NULL, 
		"INCREMENT" DECIMAL(31 , 0), 
		"START" DECIMAL(31 , 0), 
		"MAXVALUE" DECIMAL(31 , 0), 
		"MINVALUE" DECIMAL(31 , 0), 
		"CYCLE" CHAR(1) NOT NULL, 
		"CACHE" INTEGER NOT NULL, 
		"ORDER" CHAR(1) NOT NULL, 
		"ORIGIN" CHAR(1) NOT NULL, 
		"SEQTYPE" CHAR(1) NOT NULL, 
		"DATATYPEID" INTEGER NOT NULL, 
		"SEQ_DESC" BLOB(65536) INLINE LENGTH 116, 
		"CREATE_TIME" TIMESTAMP NOT NULL, 
		"ALTER_TIME" TIMESTAMP NOT NULL, 
		"SOURCETYPEID" INTEGER NOT NULL, 
		"PRECISION" SMALLINT NOT NULL, 
		"DEFINER" VARCHAR(128) NOT NULL, 
		"OWNER" VARCHAR(128) NOT NULL, 
		"DEFINERTYPE" CHAR(1) NOT NULL, 
		"OWNERTYPE" CHAR(1) NOT NULL, 
		"BASE_SEQSCHEMA" VARCHAR(128), 
		"BASE_SEQNAME" VARCHAR(128)
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSSERVEROPTIONS" (
		"WRAPNAME" VARCHAR(128), 
		"SERVERNAME" VARCHAR(128), 
		"SERVERTYPE" VARCHAR(30), 
		"SERVERVERSION" VARCHAR(18), 
		"CREATE_TIME" TIMESTAMP NOT NULL, 
		"OPTION" VARCHAR(128) NOT NULL, 
		"SETTING" VARCHAR(2048) NOT NULL, 
		"SERVEROPTIONKEY" VARCHAR(18) NOT NULL, 
		"REMARKS" VARCHAR(254)
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSSERVERS" (
		"WRAPNAME" VARCHAR(128) NOT NULL, 
		"SERVERNAME" VARCHAR(128) NOT NULL, 
		"SERVERTYPE" VARCHAR(30), 
		"SERVERVERSION" VARCHAR(18), 
		"SERVER_DESC" BLOB(10485760) INLINE LENGTH 196, 
		"REMARKS" VARCHAR(254)
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSSERVICECLASSES" (
		"SERVICECLASSNAME" VARCHAR(128) NOT NULL, 
		"SERVICECLASSID" SMALLINT NOT NULL, 
		"PARENTID" SMALLINT NOT NULL, 
		"CREATE_TIME" TIMESTAMP NOT NULL, 
		"ALTER_TIME" TIMESTAMP NOT NULL, 
		"ENABLED" CHAR(1) NOT NULL, 
		"AGENTPRIORITY" SMALLINT NOT NULL, 
		"PREFETCHPRIORITY" CHAR(1) NOT NULL, 
		"INBOUNDCORRELATOR" VARCHAR(128), 
		"OUTBOUNDCORRELATOR" VARCHAR(128), 
		"COLLECTAGGACTDATA" CHAR(1) NOT NULL, 
		"COLLECTAGGREQDATA" CHAR(1) NOT NULL, 
		"COLLECTACTDATA" CHAR(1) NOT NULL, 
		"COLLECTACTPARTITION" CHAR(1) NOT NULL, 
		"SERVICECLASS_DESC" BLOB(1048576) INLINE LENGTH 164, 
		"BUFFERPOOLPRIORITY" CHAR(1) NOT NULL, 
		"COLLECTREQMETRICS" CHAR(1) NOT NULL, 
		"MAXDEGREE" SMALLINT, 
		"CPUSHARES" INTEGER NOT NULL, 
		"CPUSHARETYPE" CHAR(1) NOT NULL, 
		"CPULIMIT" SMALLINT NOT NULL, 
		"SORTMEMORYPRIORITY" CHAR(1) NOT NULL, 
		"SECTIONACTUALSOPTIONS" VARCHAR(32) NOT NULL, 
		"COLLECTAGGUOWDATA" CHAR(1) NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSSTATEMENTTEXTS" (
		"TEXTID" INTEGER NOT NULL, 
		"TEXT" CLOB(2097152) INLINE LENGTH 164 NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSSTMT" (
		"PLNAME" VARCHAR(128) NOT NULL, 
		"PLCREATOR" VARCHAR(128) NOT NULL, 
		"STMTNO" INTEGER NOT NULL, 
		"SECTNO" SMALLINT NOT NULL, 
		"TEXT" CLOB(2097152) INLINE LENGTH 164 NOT NULL, 
		"UNIQUE_ID" CHAR (8) FOR BIT DATA NOT NULL, 
		"HOST_VARS" BLOB(4190000) INLINE LENGTH 164
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSSTOGROUPS" (
		"SGNAME" VARCHAR(128) NOT NULL, 
		"SGID" INTEGER NOT NULL, 
		"OWNER" VARCHAR(128) NOT NULL, 
		"CREATE_TIME" TIMESTAMP NOT NULL, 
		"DEFAULTSG" CHAR(1) NOT NULL, 
		"OVERHEAD" DOUBLE NOT NULL, 
		"DEVICEREADRATE" DOUBLE NOT NULL, 
		"WRITEOVERHEAD" DOUBLE, 
		"DEVICEWRITERATE" DOUBLE, 
		"DATATAG" SMALLINT NOT NULL, 
		"CACHINGTIER" SMALLINT NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSSURROGATEAUTHIDS" (
		"GRANTOR" VARCHAR(128) NOT NULL, 
		"GRANTORTYPE" CHAR(1) NOT NULL, 
		"TRUSTEDID" VARCHAR(128) NOT NULL, 
		"TRUSTEDIDTYPE" CHAR(1) NOT NULL, 
		"SURROGATEAUTHID" VARCHAR(128) NOT NULL, 
		"SURROGATEAUTHIDTYPE" CHAR(1) NOT NULL, 
		"AUTHENTICATE" CHAR(1) NOT NULL, 
		"CONTEXTROLE" VARCHAR(128), 
		"GRANT_TIME" TIMESTAMP NOT NULL, 
		"GRANTORROLEID" INTEGER
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSTABAUTH" (
		"GRANTOR" VARCHAR(128) NOT NULL, 
		"GRANTEE" VARCHAR(128) NOT NULL, 
		"TCREATOR" VARCHAR(128) NOT NULL, 
		"TTNAME" VARCHAR(128) NOT NULL, 
		"TABAUTH" SMALLINT NOT NULL, 
		"CONTROLAUTH" CHAR(1) NOT NULL, 
		"ALTERAUTH" CHAR(1) NOT NULL, 
		"DELETEAUTH" CHAR(1) NOT NULL, 
		"INDEXAUTH" CHAR(1) NOT NULL, 
		"INSERTAUTH" CHAR(1) NOT NULL, 
		"SELECTAUTH" CHAR(1) NOT NULL, 
		"UPDATEAUTH" CHAR(1) NOT NULL, 
		"REFAUTH" CHAR(1) NOT NULL, 
		"GRANTEETYPE" CHAR(1) NOT NULL, 
		"GRANTORTYPE" CHAR(1) NOT NULL, 
		"GRANTEEROLEID" INTEGER, 
		"GRANTORROLEID" INTEGER
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSTABCONST" (
		"NAME" VARCHAR(128) NOT NULL, 
		"DEFINER" VARCHAR(128) NOT NULL, 
		"CONSTRAINTYP" CHAR(1) NOT NULL, 
		"TBNAME" VARCHAR(128) NOT NULL, 
		"TBCREATOR" VARCHAR(128) NOT NULL, 
		"REMARKS" VARCHAR(254), 
		"ENFORCED" CHAR(1) NOT NULL, 
		"CHECKEXISTINGDATA" CHAR(1) NOT NULL, 
		"ENABLEQUERYOPT" CHAR(1) NOT NULL, 
		"DEFINERTYPE" CHAR(1) NOT NULL, 
		"PERIODNAME" VARCHAR(128), 
		"PERIODPOLICY" CHAR(1) NOT NULL, 
		"TRUSTED" CHAR(1) NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSTABLES" (
		"NAME" VARCHAR(128) NOT NULL, 
		"CREATOR" VARCHAR(128) NOT NULL, 
		"TYPE" CHAR(1) NOT NULL, 
		"CTIME" TIMESTAMP NOT NULL, 
		"REMARKS" VARCHAR(254), 
		"PACKED_DESC" BLOB(133169152) INLINE LENGTH 196, 
		"VIEW_DESC" BLOB(4190000) INLINE LENGTH 164, 
		"COLCOUNT" SMALLINT NOT NULL, 
		"FID" SMALLINT NOT NULL, 
		"TID" SMALLINT NOT NULL, 
		"CARD" BIGINT NOT NULL, 
		"NPAGES" BIGINT NOT NULL, 
		"FPAGES" BIGINT NOT NULL, 
		"OVERFLOW" BIGINT NOT NULL, 
		"PARENTS" SMALLINT, 
		"CHILDREN" SMALLINT, 
		"SELFREFS" SMALLINT, 
		"KEYCOLUMNS" SMALLINT, 
		"KEYOBID" SMALLINT, 
		"REL_DESC" BLOB(262144) INLINE LENGTH 140, 
		"BASE_NAME" VARCHAR(128), 
		"BASE_SCHEMA" VARCHAR(128), 
		"TBSPACE" VARCHAR(128), 
		"INDEX_TBSPACE" VARCHAR(128), 
		"LONG_TBSPACE" VARCHAR(128), 
		"KEYUNIQUE" SMALLINT NOT NULL, 
		"CHECKCOUNT" SMALLINT NOT NULL, 
		"CHECK_DESC" BLOB(131072) INLINE LENGTH 140, 
		"STATS_TIME" TIMESTAMP, 
		"DEFINER" VARCHAR(128) NOT NULL, 
		"TRIG_DESC" BLOB(3145728) INLINE LENGTH 164, 
		"DATA_CAPTURE" CHAR(1) NOT NULL, 
		"STATUS" CHAR(1) NOT NULL, 
		"CONST_CHECKED" CHAR(32) NOT NULL, 
		"PMAP_ID" SMALLINT, 
		"ENCODING_SCHEME" CHAR(1) NOT NULL, 
		"PCTFREE" SMALLINT NOT NULL, 
		"ROWTYPESCHEMA" VARCHAR(128), 
		"ROWTYPENAME" VARCHAR(128), 
		"APPEND_MODE" CHAR(1) NOT NULL, 
		"PARTITION_MODE" CHAR(1) NOT NULL, 
		"REFRESH" CHAR(1) NOT NULL, 
		"REFRESH_TIME" TIMESTAMP, 
		"LOCKSIZE" CHAR(1) NOT NULL, 
		"VOLATILE" CHAR(1) NOT NULL, 
		"REMOTE_DESC" BLOB(10485760) INLINE LENGTH 196, 
		"CLUSTERED" CHAR(1), 
		"AST_DESC" BLOB(535822336) INLINE LENGTH 220, 
		"DROPRULE" CHAR(1) NOT NULL, 
		"LOGINDEXBUILD" CHAR(1) NOT NULL, 
		"PROPERTY" VARCHAR(32) NOT NULL, 
		"STATISTICS_PROFILE" CLOB(10485760) INLINE LENGTH 196, 
		"COMPRESSION" CHAR(1) NOT NULL, 
		"ACCESS_MODE" CHAR(1) NOT NULL, 
		"ACTIVE_BLOCKS" BIGINT NOT NULL, 
		"MAXFREESPACESEARCH" SMALLINT NOT NULL, 
		"AVGCOMPRESSEDROWSIZE" SMALLINT NOT NULL, 
		"AVGROWCOMPRESSIONRATIO" REAL NOT NULL, 
		"AVGROWSIZE" SMALLINT NOT NULL, 
		"PCTROWSCOMPRESSED" REAL NOT NULL, 
		"CODEPAGE" SMALLINT NOT NULL, 
		"PCTPAGESSAVED" SMALLINT NOT NULL, 
		"LAST_REGEN_TIME" TIMESTAMP, 
		"SECPOLICYID" INTEGER NOT NULL, 
		"PROTECTIONGRANULARITY" CHAR(1) NOT NULL, 
		"INVALIDATE_TIME" TIMESTAMP NOT NULL, 
		"DEFINERTYPE" CHAR(1) NOT NULL, 
		"ALTER_TIME" TIMESTAMP NOT NULL, 
		"AUDITPOLICYID" INTEGER, 
		"COLLATIONID" CHAR (8) FOR BIT DATA NOT NULL, 
		"COLLATIONID_ORDERBY" CHAR (8) FOR BIT DATA NOT NULL, 
		"ONCOMMIT" CHAR(1) NOT NULL, 
		"ONROLLBACK" CHAR(1) NOT NULL, 
		"LOGGED" CHAR(1) NOT NULL, 
		"LASTUSED" DATE NOT NULL, 
		"CONTROL" CHAR(1) NOT NULL, 
		"CONTROLS_DESC" BLOB(4194304) INLINE LENGTH 196, 
		"ROWCOMPMODE" CHAR(1) NOT NULL, 
		"AUDITEXCEPTION_DESC" BLOB(4190000) INLINE LENGTH 164, 
		"AUDITEXCEPTIONENABLED" CHAR(1) NOT NULL, 
		"MPAGES" BIGINT NOT NULL, 
		"EXTENDED_ROW_SIZE" CHAR(1) NOT NULL, 
		"PCTEXTENDEDROWS" REAL NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSTABLESPACES" (
		"TBSPACE" VARCHAR(128) NOT NULL, 
		"DEFINER" VARCHAR(128) NOT NULL, 
		"CREATE_TIME" TIMESTAMP NOT NULL, 
		"TBSPACEID" INTEGER NOT NULL, 
		"TBSPACETYPE" CHAR(1) NOT NULL, 
		"DATATYPE" CHAR(1) NOT NULL, 
		"EXTENTSIZE" INTEGER NOT NULL, 
		"PREFETCHSIZE" INTEGER NOT NULL, 
		"OVERHEAD" DOUBLE NOT NULL, 
		"TRANSFERRATE" DOUBLE NOT NULL, 
		"REMARKS" VARCHAR(254), 
		"NGNAME" VARCHAR(128) NOT NULL, 
		"BUFFERPOOLID" INTEGER NOT NULL, 
		"PAGESIZE" INTEGER NOT NULL, 
		"DROP_RECOVERY" CHAR(1) NOT NULL, 
		"DEFINERTYPE" CHAR(1) NOT NULL, 
		"WRITEOVERHEAD" DOUBLE, 
		"WRITETRANSFERRATE" DOUBLE, 
		"SGID" INTEGER NOT NULL, 
		"DATATAG" SMALLINT NOT NULL, 
		"EFFECTIVEPREFETCHSIZE" INTEGER NOT NULL, 
		"CACHINGTIER" SMALLINT NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSTABOPTIONS" (
		"TABSCHEMA" VARCHAR(128) NOT NULL, 
		"TABNAME" VARCHAR(128) NOT NULL, 
		"OPTION" VARCHAR(128) NOT NULL, 
		"SETTING" CLOB(32768) INLINE LENGTH 116 NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSTASKS" (
		"JOBID" BIGINT NOT NULL, 
		"DBPARTITIONNUM" SMALLINT NOT NULL, 
		"STAGE" INTEGER NOT NULL, 
		"TASKID" BIGINT NOT NULL, 
		"STATE" INTEGER NOT NULL, 
		"TASKTYPE" INTEGER NOT NULL, 
		"TASKVERSION" INTEGER NOT NULL, 
		"PRIORITY" INTEGER, 
		"OBJECTTYPE" INTEGER, 
		"TBSPACEID" INTEGER, 
		"OBJECTID" INTEGER, 
		"INTERNALID" INTEGER, 
		"TASK_DESC" BLOB(4190000) INLINE LENGTH 164, 
		"CREATE_TIME" TIMESTAMP NOT NULL, 
		"MEMBER" SMALLINT NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSTBSPACEAUTH" (
		"GRANTOR" VARCHAR(128) NOT NULL, 
		"GRANTEE" VARCHAR(128) NOT NULL, 
		"GRANTEETYPE" CHAR(1) NOT NULL, 
		"TBSPACEID" INTEGER NOT NULL, 
		"USEAUTH" CHAR(1) NOT NULL, 
		"TBSPACE" VARCHAR(128) NOT NULL, 
		"GRANTORTYPE" CHAR(1) NOT NULL, 
		"GRANTEEROLEID" INTEGER, 
		"GRANTORROLEID" INTEGER
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSTHRESHOLDS" (
		"THRESHOLDNAME" VARCHAR(128) NOT NULL, 
		"THRESHOLDID" INTEGER NOT NULL, 
		"ORIGIN" CHAR(1) NOT NULL, 
		"THRESHOLDCLASS" CHAR(1) NOT NULL, 
		"THRESHOLDPREDICATE" VARCHAR(15) NOT NULL, 
		"THRESHOLDPREDICATEID" SMALLINT NOT NULL, 
		"DOMAIN" CHAR(2) NOT NULL, 
		"DOMAINID" INTEGER NOT NULL, 
		"ENFORCEMENT" CHAR(1) NOT NULL, 
		"QUEUING" CHAR(1) NOT NULL, 
		"MAXVALUE" BIGINT NOT NULL, 
		"QUEUESIZE" INTEGER NOT NULL, 
		"COLLECTACTDATA" CHAR(1) NOT NULL, 
		"COLLECTACTPARTITION" CHAR(1) NOT NULL, 
		"EXECUTION" CHAR(1) NOT NULL, 
		"ENABLED" CHAR(1) NOT NULL, 
		"CREATE_TIME" TIMESTAMP NOT NULL, 
		"ALTER_TIME" TIMESTAMP NOT NULL, 
		"THRESHOLD_DESC" BLOB(8192) INLINE LENGTH 92, 
		"REMAPSCID" SMALLINT NOT NULL, 
		"VIOLATIONRECORDLOGGED" CHAR(1) NOT NULL, 
		"CHECKINTERVAL" INTEGER NOT NULL, 
		"OVERFLOWPERCENT" SMALLINT NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSTRANSFORMS" (
		"TYPEID" SMALLINT NOT NULL, 
		"GROUPNAME" VARCHAR(128) NOT NULL, 
		"FROMSQL_FUNCID" INTEGER, 
		"TOSQL_FUNCID" INTEGER, 
		"FROMSQL_FORMAT" CHAR(1) NOT NULL, 
		"TOSQL_FORMAT" CHAR(1) NOT NULL, 
		"FROMSQL_LENGTH" INTEGER NOT NULL, 
		"ORIGIN" CHAR(1) NOT NULL, 
		"REMARKS" VARCHAR(254)
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSTRIGGERS" (
		"NAME" VARCHAR(128) NOT NULL, 
		"SCHEMA" VARCHAR(128) NOT NULL, 
		"DEFINER" VARCHAR(128) NOT NULL, 
		"TBNAME" VARCHAR(128) NOT NULL, 
		"TBCREATOR" VARCHAR(128) NOT NULL, 
		"TRIGTIME" CHAR(1) NOT NULL, 
		"TRIGEVENT" CHAR(1) NOT NULL, 
		"GRANULARITY" CHAR(1) NOT NULL, 
		"VALID" CHAR(1) NOT NULL, 
		"TEXT" CLOB(2097152) INLINE LENGTH 164 NOT NULL, 
		"CREATE_TIME" TIMESTAMP NOT NULL, 
		"FUNC_PATH" CLOB(2048) INLINE LENGTH 92 NOT NULL, 
		"REMARKS" VARCHAR(254), 
		"QUALIFIER" VARCHAR(128) NOT NULL, 
		"LAST_REGEN_TIME" TIMESTAMP NOT NULL, 
		"DEFINERTYPE" CHAR(1) NOT NULL, 
		"COLLATIONID" CHAR (8) FOR BIT DATA NOT NULL, 
		"COLLATIONID_ORDERBY" CHAR (8) FOR BIT DATA NOT NULL, 
		"SECURE" CHAR(1) NOT NULL, 
		"ALTER_TIME" TIMESTAMP NOT NULL, 
		"ENABLED" CHAR(1) NOT NULL, 
		"LIB_ID" INTEGER, 
		"DEBUG_MODE" CHAR(1) NOT NULL, 
		"STRINGUNITS" CHAR(1) NOT NULL, 
		"ENVID" INTEGER NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSTUNINGINFO" (
		"TUNINGINFONAME" VARCHAR(128) NOT NULL, 
		"TUNINGVALUE" VARCHAR (2048) FOR BIT DATA
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSTYPEMAPPINGS" (
		"TYPE_MAPPING" VARCHAR(18) NOT NULL, 
		"TYPESCHEMA" VARCHAR(128), 
		"TYPENAME" VARCHAR(128) NOT NULL, 
		"TYPEID" SMALLINT NOT NULL, 
		"SOURCETYPEID" SMALLINT NOT NULL, 
		"DEFINER" VARCHAR(128) NOT NULL, 
		"UPPER_LEN" INTEGER, 
		"UPPER_SCALE" SMALLINT, 
		"BIT_DATA" CHAR(1), 
		"WRAPNAME" VARCHAR(128), 
		"SERVERNAME" VARCHAR(128), 
		"SERVERTYPE" VARCHAR(30), 
		"SERVERVERSION" VARCHAR(18), 
		"REMOTE_TYPESCHEMA" VARCHAR(128), 
		"REMOTE_TYPENAME" VARCHAR(128) NOT NULL, 
		"REMOTE_META_TYPE" CHAR(1), 
		"REMOTE_LOWER_LEN" INTEGER, 
		"REMOTE_UPPER_LEN" INTEGER, 
		"REMOTE_LOWER_SCALE" SMALLINT, 
		"REMOTE_UPPER_SCALE" SMALLINT, 
		"REMOTE_S_OPR_P" CHAR(2), 
		"REMOTE_BIT_DATA" CHAR(1), 
		"USER_DEFINED" CHAR(1) NOT NULL, 
		"CREATE_TIME" TIMESTAMP NOT NULL, 
		"REMARKS" VARCHAR(254), 
		"MAPPINGDIRECTION" CHAR(1) NOT NULL, 
		"LOWER_LEN" INTEGER, 
		"LOWER_SCALE" SMALLINT, 
		"S_OPR_P" CHAR(2), 
		"DEFINERTYPE" CHAR(1) NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSUPGRADERUNSTATSTASKS" (
		"TABLENAME" VARCHAR(128) NOT NULL, 
		"PROFILE" CLOB(2097152) INLINE LENGTH 164, 
		"LASTRUN" CLOB(2097152) INLINE LENGTH 164, 
		"SETPROFILE" CHAR(1) NOT NULL, 
		"INVOKEPROFILE" CHAR(1) NOT NULL, 
		"ORDER" INTEGER NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSUSAGELISTS" (
		"USAGELISTSCHEMA" VARCHAR(128) NOT NULL, 
		"USAGELISTNAME" VARCHAR(128) NOT NULL, 
		"USAGELISTID" INTEGER NOT NULL, 
		"OBJECTSCHEMA" VARCHAR(128) NOT NULL, 
		"OBJECTNAME" VARCHAR(128) NOT NULL, 
		"OBJECTTYPE" CHAR(1) NOT NULL, 
		"STATUS" CHAR(1) NOT NULL, 
		"MAXLISTSIZE" INTEGER NOT NULL, 
		"WHENFULL" CHAR(1) NOT NULL, 
		"AUTOSTART" CHAR(1) NOT NULL, 
		"ACTIVEDURATION" INTEGER NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSUSERAUTH" (
		"GRANTEE" VARCHAR(128) NOT NULL, 
		"GRANTEETYPE" CHAR(1) NOT NULL, 
		"TABSCHEMA" VARCHAR(128) NOT NULL, 
		"TABNAME" VARCHAR(128) NOT NULL, 
		"AUTH_DESC" BLOB(2097152) INLINE LENGTH 164 NOT NULL, 
		"GRANTEEROLEID" INTEGER
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSUSEROPTIONS" (
		"SERVERNAME" VARCHAR(128) NOT NULL, 
		"AUTHID" VARCHAR(128) NOT NULL, 
		"OPTION" VARCHAR(128) NOT NULL, 
		"SETTING" VARCHAR(2048) NOT NULL, 
		"AUTHIDTYPE" CHAR(1) NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSVARIABLEAUTH" (
		"GRANTOR" VARCHAR(128) NOT NULL, 
		"GRANTORTYPE" CHAR(1) NOT NULL, 
		"GRANTORROLEID" INTEGER, 
		"GRANTEE" VARCHAR(128) NOT NULL, 
		"GRANTEETYPE" CHAR(1) NOT NULL, 
		"GRANTEEROLEID" INTEGER, 
		"VARID" INTEGER NOT NULL, 
		"READAUTH" CHAR(1) NOT NULL, 
		"WRITEAUTH" CHAR(1) NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSVARIABLES" (
		"VARSCHEMA" VARCHAR(128) NOT NULL, 
		"VARNAME" VARCHAR(128) NOT NULL, 
		"VARID" INTEGER NOT NULL, 
		"OWNER" VARCHAR(128) NOT NULL, 
		"OWNERTYPE" CHAR(1) NOT NULL, 
		"CREATE_TIME" TIMESTAMP NOT NULL, 
		"LAST_REGEN_TIME" TIMESTAMP NOT NULL, 
		"TYPEID" SMALLINT NOT NULL, 
		"LENGTH" INTEGER NOT NULL, 
		"SCALE" SMALLINT NOT NULL, 
		"CODEPAGE" SMALLINT NOT NULL, 
		"SCOPE" CHAR(1) NOT NULL, 
		"DEFAULT" CLOB(65536) INLINE LENGTH 116, 
		"QUALIFIER" VARCHAR(128), 
		"FUNC_PATH" CLOB(2048) INLINE LENGTH 92, 
		"VAR_DESC" BLOB(131072) INLINE LENGTH 140 NOT NULL, 
		"COLLATIONID" CHAR (8) FOR BIT DATA NOT NULL, 
		"COLLATIONID_ORDERBY" CHAR (8) FOR BIT DATA NOT NULL, 
		"VARMODULEID" INTEGER, 
		"PUBLISHED" CHAR(1) NOT NULL, 
		"VALID" CHAR(1) NOT NULL, 
		"READONLY" CHAR(1) NOT NULL, 
		"NULLS" CHAR(1) NOT NULL, 
		"STRINGUNITS" CHAR(1) NOT NULL, 
		"ENVID" INTEGER NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSVERSIONS" (
		"VERSIONNUMBER" INTEGER NOT NULL, 
		"VERSION_TIMESTAMP" TIMESTAMP NOT NULL, 
		"AUTHID" VARCHAR(128) NOT NULL, 
		"VERSIONBUILDLEVEL" VARCHAR(30)
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSVIEWDEP" (
		"BNAME" VARCHAR(128) NOT NULL, 
		"BCREATOR" VARCHAR(128) NOT NULL, 
		"BTYPE" CHAR(1) NOT NULL, 
		"DNAME" VARCHAR(128) NOT NULL, 
		"DCREATOR" VARCHAR(128) NOT NULL, 
		"VCAUTHID" VARCHAR(128) NOT NULL, 
		"TABAUTH" SMALLINT, 
		"DTYPE" CHAR(1) NOT NULL, 
		"OUTER_FROM" CHAR(1) NOT NULL, 
		"VCAUTHIDTYPE" CHAR(1) NOT NULL, 
		"BMODULEID" INTEGER
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSVIEWS" (
		"NAME" VARCHAR(128) NOT NULL, 
		"CREATOR" VARCHAR(128) NOT NULL, 
		"CHECK" CHAR(1) NOT NULL, 
		"TEXT" CLOB(2097152) INLINE LENGTH 164 NOT NULL, 
		"FUNC_PATH" CLOB(2048) INLINE LENGTH 92 NOT NULL, 
		"VALID" CHAR(1) NOT NULL, 
		"READONLY" CHAR(1) NOT NULL, 
		"DEFINER" VARCHAR(128) NOT NULL, 
		"QUALIFIER" VARCHAR(128) NOT NULL, 
		"DEFINERTYPE" CHAR(1) NOT NULL, 
		"STRINGUNITS" CHAR(1) NOT NULL, 
		"ENVID" INTEGER NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSWORKACTIONS" (
		"ACTIONNAME" VARCHAR(128) NOT NULL, 
		"ACTIONID" INTEGER NOT NULL, 
		"ACTIONSETID" INTEGER NOT NULL, 
		"WORKCLASSID" INTEGER NOT NULL, 
		"CREATE_TIME" TIMESTAMP NOT NULL, 
		"ALTER_TIME" TIMESTAMP NOT NULL, 
		"ENABLED" CHAR(1) NOT NULL, 
		"ACTIONTYPE" CHAR(1) NOT NULL, 
		"REFOBJECTID" INTEGER, 
		"SECTIONACTUALSOPTIONS" VARCHAR(32) NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSWORKACTIONSETS" (
		"ACTIONSETNAME" VARCHAR(128) NOT NULL, 
		"ACTIONSETID" INTEGER NOT NULL, 
		"WORKCLASSSETID" INTEGER NOT NULL, 
		"CREATE_TIME" TIMESTAMP NOT NULL, 
		"ALTER_TIME" TIMESTAMP NOT NULL, 
		"ENABLED" CHAR(1) NOT NULL, 
		"OBJECTTYPE" CHAR(1) NOT NULL, 
		"OBJECTID" INTEGER NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSWORKCLASSATTRIBUTES" (
		"WORKCLASSID" INTEGER NOT NULL, 
		"TYPEID" SMALLINT NOT NULL, 
		"VALUE1" DOUBLE, 
		"VALUE2" DOUBLE, 
		"VALUE3" VARCHAR(128), 
		"WORKCLASSATTR_DESC" BLOB(8192) INLINE LENGTH 92
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSWORKCLASSES" (
		"WORKCLASSNAME" VARCHAR(128) NOT NULL, 
		"WORKCLASSID" INTEGER NOT NULL, 
		"WORKCLASSSETID" INTEGER NOT NULL, 
		"CREATE_TIME" TIMESTAMP NOT NULL, 
		"ALTER_TIME" TIMESTAMP NOT NULL, 
		"EVALUATIONORDER" SMALLINT NOT NULL, 
		"WORKCLASS_DESC" BLOB(8192) INLINE LENGTH 92
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSWORKCLASSSETS" (
		"WORKCLASSSETNAME" VARCHAR(128) NOT NULL, 
		"WORKCLASSSETID" INTEGER NOT NULL, 
		"CREATE_TIME" TIMESTAMP NOT NULL, 
		"ALTER_TIME" TIMESTAMP NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSWORKLOADAUTH" (
		"GRANTOR" VARCHAR(128) NOT NULL, 
		"GRANTORTYPE" CHAR(1) NOT NULL, 
		"GRANTORROLEID" INTEGER, 
		"GRANTEE" VARCHAR(128) NOT NULL, 
		"GRANTEETYPE" CHAR(1) NOT NULL, 
		"GRANTEEROLEID" INTEGER, 
		"WORKLOADID" INTEGER NOT NULL, 
		"USAGEAUTH" CHAR(1) NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSWORKLOADCONNATTR" (
		"WORKLOADID" INTEGER NOT NULL, 
		"CONNATTRID" SMALLINT NOT NULL, 
		"CONNATTRVALUE" VARCHAR(1000) NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSWORKLOADS" (
		"WORKLOADNAME" VARCHAR(128) NOT NULL, 
		"WORKLOADID" INTEGER NOT NULL, 
		"EVALUATIONORDER" SMALLINT NOT NULL, 
		"CREATE_TIME" TIMESTAMP NOT NULL, 
		"ALTER_TIME" TIMESTAMP NOT NULL, 
		"ENABLED" CHAR(1) NOT NULL, 
		"ALLOWACCESS" CHAR(1) NOT NULL, 
		"SERVICECLASSID" SMALLINT NOT NULL, 
		"COLLECTAGGACTDATA" CHAR(1) NOT NULL, 
		"COLLECTACTDATA" CHAR(1) NOT NULL, 
		"COLLECTACTPARTITION" CHAR(1) NOT NULL, 
		"EXTERNALNAME" VARCHAR(128), 
		"WORKLOAD_DESC" BLOB(8192) INLINE LENGTH 92, 
		"COLLECTDEADLOCK" CHAR(1) NOT NULL, 
		"COLLECTLOCKTIMEOUT" CHAR(1) NOT NULL, 
		"COLLECTLOCKWAIT" CHAR(1) NOT NULL, 
		"LOCKWAITVALUE" INTEGER NOT NULL, 
		"COLLECTACTMETRICS" CHAR(1) NOT NULL, 
		"COLLECTUOWDATAOPTIONS" VARCHAR(32) NOT NULL, 
		"MAXDEGREE" SMALLINT NOT NULL, 
		"SECTIONACTUALSOPTIONS" VARCHAR(32) NOT NULL, 
		"COLLECTAGGUOWDATA" CHAR(1) NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSWRAPOPTIONS" (
		"WRAPNAME" VARCHAR(128) NOT NULL, 
		"OPTION" VARCHAR(128) NOT NULL, 
		"SETTING" VARCHAR(2048) NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSWRAPPERS" (
		"WRAPNAME" VARCHAR(128) NOT NULL, 
		"WRAPTYPE" CHAR(1) NOT NULL, 
		"WRAPVERSION" INTEGER NOT NULL, 
		"LIBRARY" VARCHAR(255) NOT NULL, 
		"REMARKS" VARCHAR(254)
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSXDBMAPGRAPHS" (
		"XSROBJECTID" BIGINT NOT NULL, 
		"SCHEMAGRAPHID" INTEGER NOT NULL, 
		"NAMESPACEID" INTEGER NOT NULL, 
		"ROOTELEMENTID" INTEGER NOT NULL, 
		"SCHEMAGRAPH" BLOB(10485760) INLINE LENGTH 196 NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSXDBMAPSHREDTREES" (
		"XSROBJECTID" BIGINT NOT NULL, 
		"SCHEMAGRAPHID" INTEGER NOT NULL, 
		"SHREDTREEID" INTEGER NOT NULL, 
		"SHREDTREE" BLOB(10485760) INLINE LENGTH 196 NOT NULL, 
		"MAPPINGDESCRIPTION" CLOB(1048576) INLINE LENGTH 164
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSXMLPATHS" (
		"PATHID" INTEGER NOT NULL, 
		"PATHTYPE" CHAR (1) FOR BIT DATA NOT NULL, 
		"PATH" VARCHAR (1000) FOR BIT DATA NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSXMLSTRINGS" (
		"STRINGID" INTEGER NOT NULL, 
		"STRING" VARCHAR (1001) FOR BIT DATA NOT NULL, 
		"IS_TEMPORARY" CHAR(1) NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSXSROBJECTAUTH" (
		"GRANTOR" VARCHAR(128) NOT NULL, 
		"GRANTEE" VARCHAR(128) NOT NULL, 
		"GRANTEETYPE" CHAR(1) NOT NULL, 
		"XSROBJECTID" BIGINT NOT NULL, 
		"USAGEAUTH" CHAR(1) NOT NULL, 
		"GRANTORTYPE" CHAR(1) NOT NULL, 
		"GRANTEEROLEID" INTEGER, 
		"GRANTORROLEID" INTEGER
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSXSROBJECTCOMPONENTS" (
		"XSRCOMPONENTID" BIGINT NOT NULL, 
		"TARGETNAMESPACEID" INTEGER NOT NULL, 
		"SCHEMALOCATIONID" INTEGER NOT NULL, 
		"VERSIONID" INTEGER NOT NULL, 
		"COMPONENT" BLOB(31457280) INLINE LENGTH 196 NOT NULL, 
		"DIGEST" CHAR (16) FOR BIT DATA NOT NULL, 
		"PROPERTIES" BLOB(4190000) INLINE LENGTH 164, 
		"CREATE_TIME" TIMESTAMP NOT NULL, 
		"STATUS" CHAR(1) NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSXSROBJECTHIERARCHIES" (
		"XSROBJECTID" BIGINT NOT NULL, 
		"XSRCOMPONENTID" BIGINT NOT NULL, 
		"HTYPE" CHAR(1) NOT NULL, 
		"TARGETNAMESPACEID" INTEGER NOT NULL, 
		"SCHEMALOCATIONID" INTEGER NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSIBM"."SYSXSROBJECTS" (
		"XSROBJECTID" BIGINT NOT NULL, 
		"XSROBJECTSCHEMA" VARCHAR(128) NOT NULL, 
		"XSROBJECTNAME" VARCHAR(128) NOT NULL, 
		"TARGETNAMESPACEID" INTEGER NOT NULL, 
		"SCHEMALOCATIONID" INTEGER NOT NULL, 
		"VERSIONID" INTEGER NOT NULL, 
		"OBJECTINFO" XML, 
		"GRAMMAR" BLOB(133169152) INLINE LENGTH 196, 
		"PROPERTIES" BLOB(4190000) INLINE LENGTH 164, 
		"OBJECTTYPE" CHAR(1) NOT NULL, 
		"OWNER" VARCHAR(128) NOT NULL, 
		"CREATE_TIME" TIMESTAMP NOT NULL, 
		"ALTER_TIME" TIMESTAMP NOT NULL, 
		"STATUS" CHAR(1) NOT NULL, 
		"DECOMPOSITION" CHAR(1) NOT NULL, 
		"DECOMPOSITION_VERSION" VARCHAR(20), 
		"OWNERTYPE" CHAR(1) NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSCATSPACE"
	COMPRESS NO;

CREATE TABLE "SYSTOOLS"."HMON_ATM_INFO" (
		"SCHEMA" VARCHAR(128) NOT NULL, 
		"NAME" VARCHAR(128) NOT NULL, 
		"CREATE_TIME" TIMESTAMP NOT NULL, 
		"STATS_FLAG" CHAR(1) NOT NULL DEFAULT 'N', 
		"STATS_LOCK" CHAR(1) NOT NULL DEFAULT 'N', 
		"STATS_OPTS" INTEGER NOT NULL DEFAULT 0, 
		"LAST_WAIT" INTEGER NOT NULL DEFAULT 4, 
		"TO_WAIT" INTEGER NOT NULL DEFAULT 1, 
		"SIGNAL" CHAR(1) NOT NULL DEFAULT 'N', 
		"LEO_TAB" CHAR(1) NOT NULL DEFAULT 'N', 
		"EXEC_COUNT" BIGINT NOT NULL DEFAULT 0, 
		"STATS_STATE" SMALLINT NOT NULL DEFAULT 0, 
		"STATS_NOTIFY" CHAR(1) NOT NULL DEFAULT 'N', 
		"STATS_DETAIL" VARCHAR(200), 
		"STATS_HISTORY" VARCHAR (200) FOR BIT DATA, 
		"STATS_TIME" TIMESTAMP, 
		"REORG_FLAG" CHAR(1) NOT NULL DEFAULT 'N', 
		"REORG_LOCK" CHAR(1) NOT NULL DEFAULT 'N', 
		"REORG_STATE" SMALLINT NOT NULL DEFAULT 0, 
		"REORG_TIME" TIMESTAMP, 
		"REORG_NOTIFY" CHAR(1) NOT NULL DEFAULT 'N', 
		"REORG_DETAIL" VARCHAR(200), 
		"REORG_HISTORY" VARCHAR (200) FOR BIT DATA, 
		"REORG_AVG_RUNTIME" INTEGER, 
		"REORG_INDEX_SCHEMA" VARCHAR(128), 
		"REORG_INDEX_NAME" VARCHAR(128), 
		"REORG_INDEX_ONLINE" CHAR(1)
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSTOOLSPACE"
	COMPRESS NO;

CREATE TABLE "SYSTOOLS"."HMON_COLLECTION" (
		"HI_ID" BIGINT NOT NULL, 
		"OBJ_NAME1" VARCHAR(128) NOT NULL, 
		"OBJ_NAME2" VARCHAR(128) NOT NULL DEFAULT '', 
		"OBJ_NAME3" VARCHAR(128) NOT NULL DEFAULT '', 
		"OBJ_DETAIL" VARCHAR(512), 
		"OBJ_STATE" INTEGER NOT NULL, 
		"OBJ_REFRESH_TIME" TIMESTAMP NOT NULL, 
		"NOTIFY" CHAR(1) NOT NULL DEFAULT 'N', 
		"HISTORY" VARCHAR (200) FOR BIT DATA
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSTOOLSPACE"
	COMPRESS NO;

CREATE TABLE "SYSTOOLS"."POLICY" (
		"MED" VARCHAR(128) NOT NULL, 
		"DECISION" VARCHAR(128) NOT NULL, 
		"NAME" VARCHAR(128) NOT NULL, 
		"UPDATE_TIME" TIMESTAMP NOT NULL, 
		"POLICY" BLOB(2097152) INLINE LENGTH 164
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SYSTOOLSPACE"
	COMPRESS NO;

CREATE TABLE "WXODBC3"."BLOBTYPES" (
		"IDBLOBTYPES" INTEGER NOT NULL, 
		"BLOB" BLOB(16) INLINE LENGTH 68
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "USERSPACE1"
	COMPRESS NO;

CREATE TABLE "WXODBC3"."CHARTYPES" (
		"IDCHARTYPES" INTEGER NOT NULL, 
		"VARCHAR" VARCHAR(128), 
		"CHAR" CHAR(128)
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "USERSPACE1"
	COMPRESS NO;

CREATE TABLE "WXODBC3"."DATETYPES" (
		"IDDATETYPES" INTEGER NOT NULL, 
		"DATE" DATE, 
		"TIME" TIME, 
		"TIMETAMP" TIMESTAMP
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "USERSPACE1"
	COMPRESS NO;

CREATE TABLE "WXODBC3"."FLOATTYPES" (
		"IDFLOATTYPES" INTEGER NOT NULL, 
		"DOUBLE" DOUBLE, 
		"FLOAT" DOUBLE
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "USERSPACE1"
	COMPRESS NO;

CREATE TABLE "WXODBC3"."INTEGERTYPES" (
		"IDINTEGERTYPES" INTEGER NOT NULL, 
		"SMALLINT" SMALLINT, 
		"INT" INTEGER, 
		"BIGINT" BIGINT
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "USERSPACE1"
	COMPRESS NO;

CREATE TABLE "WXODBC3"."NUMERICTYPES" (
		"IDNUMERICTYPES" INTEGER NOT NULL, 
		"DECIMAL_18_0" DECIMAL(18 , 0), 
		"DECIMAL_18_10" DECIMAL(18 , 10)
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "USERSPACE1"
	COMPRESS NO;

ALTER TABLE "SYSTOOLS"."HMON_ATM_INFO" ADD CONSTRAINT "ATM_UNIQ" UNIQUE
	("SCHEMA", 
	 "NAME");

ALTER TABLE "SYSTOOLS"."HMON_COLLECTION" ADD CONSTRAINT "HI_OBJ_UNIQ" UNIQUE
	("HI_ID", 
	 "OBJ_NAME1", 
	 "OBJ_NAME2", 
	 "OBJ_NAME3");

ALTER TABLE "SYSTOOLS"."POLICY" ADD CONSTRAINT "POLICY_UNQ" UNIQUE
	("MED", 
	 "DECISION", 
	 "NAME");

ALTER TABLE "WXODBC3"."BLOBTYPES" ADD CONSTRAINT "SQL140713172005040" PRIMARY KEY
	("IDBLOBTYPES");

ALTER TABLE "WXODBC3"."CHARTYPES" ADD CONSTRAINT "SQL140223170703300" PRIMARY KEY
	("IDCHARTYPES");

ALTER TABLE "WXODBC3"."DATETYPES" ADD CONSTRAINT "SQL140223221611740" PRIMARY KEY
	("IDDATETYPES");

ALTER TABLE "WXODBC3"."FLOATTYPES" ADD CONSTRAINT "SQL140223172006570" PRIMARY KEY
	("IDFLOATTYPES");

ALTER TABLE "WXODBC3"."INTEGERTYPES" ADD CONSTRAINT "SQL140223170050240" PRIMARY KEY
	("IDINTEGERTYPES");

ALTER TABLE "WXODBC3"."NUMERICTYPES" ADD CONSTRAINT "SQL140713150131550" PRIMARY KEY
	("IDNUMERICTYPES");

